'use client';
import {lazy,Suspense,useCallback,useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress as ProgressMeter} from '@/components/ui/progress';
import {NativeSelect} from '@/components/ui/native-select';
import {Code2,Play,BookOpen,Timer,CheckCircle2,ChevronLeft,ChevronRight,Search,ArrowUpRight,Download,RotateCcw,Square,Terminal,FolderOpen,Lightbulb,Bookmark,Check,LayoutList,BarChart3,FileText,Clock3,Layers,Home as HomeIcon,Pause,Maximize2,Minimize2} from 'lucide-react';
const Editor = lazy(() => import('./Editor'));
import Discover from './Discover';
import {motion,MotionConfig,AnimatePresence} from 'motion/react';
import bank from './problems.json';
import {composePaper,budgets,finishRecord,references,validateSaved,type Attempt,type Progress,type Exam,type Saved,type ExamRecord,type LabSession,topics} from './study';
const Palette=lazy(()=>import('./Palette'));
const ProgressPanel=lazy(()=>import('./StudyPanels').then(m=>({default:m.ProgressPanel})));
const PapersPanel=lazy(()=>import('./StudyPanels').then(m=>({default:m.PapersPanel})));
const LabPractice=lazy(()=>import('./StudyPanels').then(m=>({default:m.LabPractice})));
const SessionHistory=lazy(()=>import('./StudyPanels').then(m=>({default:m.SessionHistory})));
const SolutionGuide=lazy(()=>import('./SolutionGuide'));
function EditorSkeleton({label="Loading workspace"}:{label?:string}){return <div className="editor-skeleton" role="status" aria-label={label}><span className="sr-only">{label}…</span>{[65,45,72,35,60,40].map((width,i)=><div key={i}><small>{i+1}</small><i style={{width:`${width}%`,marginLeft:`${i%3*20}px`}}/></div>)}</div>}



type Problem=(typeof bank)[number];
type Result={label:string;passed:boolean;actual?:unknown;expected?:unknown;expression?:string;error?:string;stdout?:string;stderr?:string;raw?:string};
const KEY='practical9569.v1';
const asset=(path:string)=>import.meta.env.BASE_URL+path.replace(/^\//,'');
const display=(v:unknown)=>JSON.stringify(v,null,2);
function download(name:string,content:string,type='text/plain'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function clock(seconds:number){return [Math.floor(seconds/3600),Math.floor(seconds/60)%60,seconds%60].map(n=>String(n).padStart(2,'0')).join(':');}
export default function Home(){
 const [selected,setSelected]=useState('first-match');const [progress,setProgress]=useState<Record<string,Progress>>({});const [loaded,setLoaded]=useState(false);const [notice,setNotice]=useState('');
 const [confirmAction,setConfirmAction]=useState<'reset'|'end'|null>(null);
 const [examHistory,setExamHistory]=useState<ExamRecord[]>([]);const [labSessions,setLabSessions]=useState<LabSession[]>([]);const [examDate,setExamDate]=useState('');const [theme,setTheme]=useState<'system'|'light'|'dark'>('system');const [paletteOpen,setPaletteOpen]=useState(false);const [refFilter,setRefFilter]=useState('');const [coverageTarget,setCoverageTarget]=useState('');
 const [view,setView]=useState('home');const [motionPaused,setMotionPaused]=useState(false);const [focusMode,setFocusMode]=useState(false);const [tab,setTab]=useState('Description');const [topic,setTopic]=useState('All topics');const [level,setLevel]=useState('All levels');const [source,setSource]=useState('All sources');const [query,setQuery]=useState('');const [onlySaved,setOnlySaved]=useState(false);
 const [results,setResults]=useState<Result[]>([]);const [busy,setBusy]=useState(false);const [runStatus,setRunStatus]=useState('');const [stdin,setStdin]=useState('');const [customExpr,setCustomExpr]=useState('');const [customExpected,setCustomExpected]=useState('');const [showCustom,setShowCustom]=useState(false);const [hintCount,setHintCount]=useState(0);const [showSolution,setShowSolution]=useState(false);
 const [exam,setExam]=useState<Exam|null>(null);const [now,setNow]=useState(Date.now());const [mockIds,setMockIds]=useState(['inventory-pipeline','linked-free','transaction','flask-lab']);
 const worker=useRef<Worker|null>(null);const timeout=useRef<ReturnType<typeof setTimeout>|null>(null);const importRef=useRef<HTMLInputElement>(null);
 const p=bank.find(x=>x.id===selected) || bank[0];const item=progress[p.id]||{};const code=item.code??p.starter;
 const solved=bank.filter(x=>progress[x.id]?.solved).length;const labs=bank.filter(x=>x.kind==='lab'&&progress[x.id]?.reviewed).length;
 const filtered=bank.filter(x=>(topic==='All topics'||x.topic===topic)&&(level==='All levels'||x.level===level)&&(source==='All sources'||x.source.includes(source))&&(!onlySaved||progress[x.id]?.bookmarked)&&(!refFilter||references(x.ref).includes(refFilter))&&`${x.title} ${x.description} ${x.source} ${x.ref}`.toLowerCase().includes(query.toLowerCase()));
 const update=useCallback((id:string,data:Partial<Progress>)=>setProgress(prev=>({...prev,[id]:{...prev[id],...data}})),[]);
 const stop=useCallback((message='Execution stopped.')=>{worker.current?.terminate();worker.current=null;if(timeout.current)clearTimeout(timeout.current);setBusy(false);setRunStatus(message)},[]);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw){const saved=validateSaved(JSON.parse(raw));setProgress(saved.progress);setExam(saved.exam);setSelected(saved.selected);setExamHistory(saved.examHistory||[]);setLabSessions(saved.labSessions||[]);setExamDate(saved.examDate||'');setTheme(saved.theme||'system')}}catch{setNotice('Saved data could not be loaded. Import a backup or export your work before continuing.')}setLoaded(true);return()=>{worker.current?.terminate();if(timeout.current)clearTimeout(timeout.current)}},[]);
 useEffect(()=>{if(!loaded)return;try{localStorage.setItem(KEY,JSON.stringify({version:1,progress,exam,selected,examHistory,labSessions,examDate,theme}));}catch{setNotice('Device storage is full or unavailable. Export a backup to keep your work.')}},[progress,exam,selected,loaded,examHistory,labSessions,examDate,theme]);
 useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPaletteOpen(value=>!value)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
 useEffect(()=>{if(exam?.finished){const record=finishRecord(exam,progress,labSessions);setExamHistory(prev=>prev.some(e=>e.id===record.id)?prev:[record,...prev])}},[exam,progress,labSessions]);
 useEffect(()=>{if(!exam||exam.finished)return;const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[exam]);
 useEffect(()=>{if(exam&&!exam.finished&&now>=exam.end){stop('Time is up.');setExam({...exam,finished:true,finishedAt:exam.end});setNotice('Time is up. Your work is saved; review or export your answers.')}},[exam,now]);
 const choose=useCallback((id:string)=>{if(!bank.some(x=>x.id===id))throw Error('Unknown challenge');stop('');setSelected(id);setView('practice');setTab('Description');setResults([]);setHintCount(0);setShowSolution(false);setCustomExpr('');setCustomExpected('');setStdin('')},[stop]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'list_practice_challenges',description:'Read the challenge bank and current device-local completion status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>bank.map(x=>({id:x.id,title:x.title,topic:x.topic,level:x.level,solved:!!progress[x.id]?.solved}))},{name:'open_practice_challenge',description:'Open a challenge in the visible practice editor; stops any running code.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||!('id' in input)||typeof input.id!=='string'||!bank.some(x=>x.id===input.id))throw Error('Provide a valid challenge id');choose(input.id);return {opened:input.id}}}];for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}return()=>lifecycle.abort()},[choose,progress]);
 function run(submit=false,custom=false){
  if(busy||p.kind==='lab')return;
  let tests=submit?p.tests:p.tests.slice(0,Math.min(2,p.tests.length));
  if(custom){try{if(!customExpr.trim())throw Error('Enter a Python expression.');tests=[{label:'Your test',expr:customExpr,expected:JSON.parse(customExpected)}]}catch{setRunStatus('Enter a Python expression and a valid JSON expected value.');return}}
  setResults([]);setBusy(true);setRunStatus('Loading Python. The first run needs an internet connection…');
  const w=new Worker(asset('/python-worker.js'));worker.current=w;
  timeout.current=setTimeout(()=>stop('Python could not load in time. Check your connection and try again.'),90000);
  w.onerror=()=>stop('Python could not start. Check your connection, then try again.');
  w.onmessage=({data})=>{
   if(data.type==='status')setRunStatus(data.message);
   if(data.type==='executing'){if(timeout.current)clearTimeout(timeout.current);timeout.current=setTimeout(()=>stop('Time limit reached (10 seconds). Check for an infinite loop or recursion.'),10000);setRunStatus('Running your code…')}
   if(data.type==='error')stop(data.message);
   if(data.type==='result'){
    const rows=data.results as Result[];const passed=rows.filter(r=>r.passed).length;stop('');setResults(rows);setRunStatus(`${passed} / ${rows.length} tests passed${submit?' · Submission recorded':''}`);
    if(submit)setProgress(prev=>({...prev,[p.id]:{...prev[p.id],solved:prev[p.id]?.solved||passed===rows.length,attempts:[{at:new Date().toISOString(),passed,total:rows.length,code,sessionId:exam&&!exam.finished?exam.id:undefined},...(prev[p.id]?.attempts||[])].slice(0,20)}}));
   }
  };
  w.postMessage({problem:p,code,tests,stdin});
 }
 function startExam(ids=mockIds,title='Mixed practice'){if(exam&&!exam.finished){setView('exam');setNotice('End the current session before starting another.');return}if(!ids.length||new Set(ids).size!==ids.length){setNotice('Choose different challenges for each task.');return}const startedAt=Date.now();const fresh={id:crypto.randomUUID(),startedAt,end:startedAt+3*60*60*1000,ids,finished:false,title};setExam(fresh);setNow(startedAt);choose(ids[0]);setNotice('Three-hour practice started. Task budgets are suggestions; hints and solutions are hidden.');}
 function exportWork(){download('practical-9569-backup.json',JSON.stringify({version:1,progress,exam,selected,examHistory,labSessions,examDate,theme},null,2),'application/json')}
 async function importWork(file?:File){if(!file)return;try{const data=validateSaved(JSON.parse(await file.text()));setProgress(prev=>({...prev,...data.progress}));setExamHistory(prev=>[...new Map([...prev,...data.examHistory||[]].map(e=>[e.id,e])).values()].sort((a,b)=>b.startedAt-a.startedAt));setLabSessions(prev=>[...new Map([...prev,...data.labSessions||[]].map(e=>[e.id,e])).values()].sort((a,b)=>b.startedAt-a.startedAt));if(data.examDate)setExamDate(data.examDate);if(data.theme)setTheme(data.theme);if(data.exam&&(!exam||exam.finished))setExam(data.exam);setNotice('Backup restored: drafts, progress, session history and preferences. An active exam is kept.')}catch{setNotice('This is not a valid Practical / 9569 backup. Your current work is unchanged.')}if(importRef.current)importRef.current.value=''}
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});},[view]);
 const activeExam=!!exam&&!exam.finished;const checked=item.checks||[];
 const selectFilter=(value:string)=>{setTopic(value);setLevel('All levels');setSource('All sources');setOnlySaved(false);setQuery('');setRefFilter('');setView('library')};
 const selectRef=(ref:string)=>{setRefFilter(ref);setTopic('All topics');setLevel('All levels');setSource('All sources');setOnlySaved(false);setQuery('');setView('library')};
 return <MotionConfig reducedMotion={motionPaused?'always':'user'}><main className={motionPaused?'motion-paused':''}>
 <a className="skip-link" href="#workspace-content">Skip to content</a>
 <header className="global-header"><div className="global-inner"><a className="brand" href={import.meta.env.BASE_URL} onClick={e=>{e.preventDefault();setView('home')}} aria-label="Practical home"><Code2 size={23}/><span>practical<span className="brand-number">9569</span></span></a><nav className="global-nav" aria-label="Main navigation">{[['home','Discover',HomeIcon],['library','Challenges',LayoutList],['practice','Workspace',Code2],['progress','Progress',BarChart3],['papers','Sources',BookOpen]].map(([id,label,Icon])=>{const NavIcon=Icon as typeof Code2;return <button key={id as string} aria-current={view===id?'page':undefined} onClick={()=>setView(id as string)} className={view===id?'navactive':''}><NavIcon size={17}/><span>{label as string}</span>{view===id&&<motion.i layoutId="navigation-indicator" transition={{type:'spring',stiffness:360,damping:32}}/>}</button>})}</nav><div className="global-actions"><button className="palette-trigger" onClick={()=>setPaletteOpen(true)} aria-label="Open quick actions"><Search size={16}/><kbd>⌘K</kbd></button><button className="motion-toggle" aria-label={motionPaused?'Enable decorative motion':'Pause decorative motion'} aria-pressed={motionPaused} title={motionPaused?'Enable motion':'Pause motion'} onClick={()=>setMotionPaused(!motionPaused)}>{motionPaused?<Play size={15}/>:<Pause size={15}/>}</button><Button className="timerbutton" onClick={()=>setView('exam')}><Timer/>{activeExam?clock(Math.max(0,Math.ceil((exam!.end-now)/1000))):'Exam practice'}</Button></div></div></header>
 {notice&&<div className="notice" role="status">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}>×</button></div>}
 {view==='practice'&&<div className="workspace-toolbar"><div><button className="text-link" onClick={()=>setView('library')}><ChevronLeft size={16}/> Challenges</button><span className="workspace-current">{p.title}</span></div><button className="focus-control" aria-pressed={focusMode} onClick={()=>setFocusMode(!focusMode)}>{focusMode?<Minimize2 size={16}/>:<Maximize2 size={16}/>} {focusMode?'Show question':'Focus on code'}</button></div>}
 <div className={'workspace '+(view==='practice'?'practice-layout':'overview')+(focusMode?' focus-mode':'')}>
 <AnimatePresence mode="wait" initial={false}><motion.div key={view} className="workspace-content" id="workspace-content" tabIndex={-1} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-4}} transition={{duration:.18}}>
 {view==='home'&&<Discover onBrowse={()=>setView('library')} onTopic={selectFilter} onResume={()=>choose(p.id)} onExam={()=>setView('exam')} title={p.title} solved={solved} count={bank.length} examDate={examDate} onExamDate={setExamDate} motionPaused={motionPaused}/>}
 {view==='practice'?<>
 <Tabs className="problem" value={tab} onValueChange={value=>setTab(String(value))} render={<section/>}><TabsList className="sectionbar tabs" aria-label="Problem sections">{['Description','Hints','Solution','Files'].map(t=><TabsTrigger key={t} value={t} className={tab===t?'selected':''}>{t}</TabsTrigger>)}</TabsList><TabsContent value={tab} key={tab} render={<article/>}><div className="problemnav"><span className="eyebrow">Challenge {String(bank.indexOf(p)+1).padStart(2,'0')} · {p.topic}</span><div><Button variant="ghost" size="icon" aria-label="Previous challenge" disabled={bank.indexOf(p)===0} onClick={()=>choose(bank[bank.indexOf(p)-1].id)}><ChevronLeft/></Button><Button variant="ghost" size="icon" aria-label="Next challenge" disabled={bank.indexOf(p)===bank.length-1} onClick={()=>choose(bank[bank.indexOf(p)+1].id)}><ChevronRight/></Button></div></div><h1>{p.title}</h1><div className="tags"><span className={p.level==='Foundation'?'easy':p.level==='Stretch'?'stretch':''}>{p.level}</span><span><Clock3 size={12}/>{p.minutes} min</span><span>{p.kind==='lab'?'Local lab':p.kind==='sql'?'SQLite':'Python 3'}</span>{item.solved&&<span className="easy">Solved <Check size={12}/></span>}<button className={item.bookmarked?'saved':''} aria-label={item.bookmarked?'Remove bookmark':'Bookmark challenge'} onClick={()=>update(p.id,{bookmarked:!item.bookmarked})}><Bookmark size={16} fill={item.bookmarked?'currentColor':'none'}/></button></div>
 {tab==='Description'&&<><p className="statement">{p.description}</p>{p.tests.slice(0,2).map((t,i)=><div key={t.label}><h3>Example {i+1} <span className="subtle">{t.label}</span></h3><pre><span className="code-label">CALL</span>{t.expr}<br/><br/><span className="code-label">EXPECTED</span>{display(t.expected)}</pre></div>)}{p.kind==='lab'&&<div className="labcallout"><FolderOpen/><h3>Complete this on your computer</h3><p>The pack contains starter files, data, instructions, and a separate solution. Use the checklist to review your work.</p><a className="downloadlink" href={asset(`/labs/${p.id}.zip`)} download>Download lab pack <Download size={16}/></a></div>}<div className="reference"><span>Syllabus {p.ref}</span><p>{p.source}{p.sourceUrl&&<> · <a href={p.sourceUrl} target="_blank" rel="noreferrer">View source <ArrowUpRight size={12}/></a></>}</p><p>Adapted prompts and fresh tests for this workspace. Output checks assess behaviour; review algorithm choice, code quality and test coverage yourself.</p></div></>}
 {tab==='Hints'&&(activeExam?<p>Hints are hidden during your timed session. End the session to review them.</p>:<><h3>Hints</h3><p>Try normal, boundary and invalid inputs before revealing a hint.</p>{p.hints.slice(0,hintCount).map((h,i)=><div className="hint" key={h}><Lightbulb size={18}/><div><strong>Hint {i+1}</strong><p>{h}</p></div></div>)}<Button variant="outline" disabled={hintCount>=p.hints.length} onClick={()=>setHintCount(hintCount+1)}>{hintCount>=p.hints.length?'All hints revealed':'Reveal next hint'}</Button></>)}
 {tab==='Solution'&&(activeExam?<p>Solutions are hidden during your timed session.</p>:<><h3>Reference solution</h3><p>Check your algorithm, edge cases and naming. Reading a solution does not mark a challenge solved.</p>{showSolution?<><Suspense fallback={<EditorSkeleton/>}><SolutionGuide id={p.id} solution={p.solution}/></Suspense><Button variant="outline" onClick={()=>download(p.id+'-reference.'+(p.kind==='sql'?'sql':'py'),p.solution)}>Download reference <Download/></Button>{p.kind==='lab'&&<p>The lab pack contains the complete reference project and local checks.</p>}</>:<Button variant="outline" onClick={()=>setShowSolution(true)}>Reveal reference solution</Button>}</>)}
 {tab==='Files'&&<><h3>Practice files</h3>{Object.keys(p.files).length?Object.entries(p.files).map(([name,content])=><div key={name}><div className="filerow"><strong>{name}</strong><Button size="sm" variant="ghost" onClick={()=>download(name,content as string)}><Download/> Save</Button></div><pre>{content as string}</pre></div>):<p>{p.kind==='lab'?'Download the full project below.':'No input files are required for this challenge.'}</p>}{p.kind==='lab'&&<a className="downloadlink" href={asset(`/labs/${p.id}.zip`)} download>Download lab pack <Download size={16}/></a>}<p>Browser exercises use a fresh temporary folder for every test. Your real computer files are not modified.</p></>}
 </TabsContent></Tabs>
 <section className="coding"><div className="sectionbar"><Code2 size={16}/>{p.kind==='sql'?'query.sql':'solution.py'}<span>{p.kind==='lab'?'Local lab notes':p.kind==='sql'?'SQLite':'Python 3'}</span><Button size="icon" variant="ghost" aria-label="Download your code" onClick={()=>download(p.id+'.'+(p.kind==='sql'?'sql':'py'),code)}><Download/></Button><Button size="icon" variant="ghost" aria-label="Restore starter code" onClick={()=>setConfirmAction('reset')}><RotateCcw/></Button></div><Suspense fallback={<EditorSkeleton label="Loading editor"/>}><Editor key={p.id} value={code} onChange={value=>update(p.id,{code:value})} kind={p.kind}/></Suspense>
 <div className="runbar"><span>{loaded?'Draft saved on this device':'Loading saved draft…'}</span>{p.kind!=='lab'&&(busy?<Button variant="outline" onClick={()=>stop()}><Square/> Stop</Button>:<><Button variant="outline" onClick={()=>run()}><Play/> Run examples</Button><Button onClick={()=>run(true)}>Submit <ChevronRight/></Button></>)}</div>
 <div className="console"><div className="consolehead"><h3><Terminal size={16}/>{p.kind==='lab'?'Self-assessment':'Test results'}</h3>{p.kind!=='lab'&&<button onClick={()=>setShowCustom(!showCustom)}>{showCustom?'Hide custom test':'+ Custom test'}</button>}</div>
 {p.kind==='lab'?<><Suspense fallback={<EditorSkeleton/>}><LabPractice key={p.id} problem={p} sessions={labSessions} onChange={setLabSessions} examId={activeExam?exam?.id:undefined} onReview={(checks,notes)=>update(p.id,{checks,notes,reviewed:checks.length===p.rubric.length})}/></Suspense><p>Quick review checklist</p>{p.rubric.map((r,i)=><label className="checkrow" key={r}><input type="checkbox" checked={checked.includes(i)} onChange={()=>update(p.id,{checks:checked.includes(i)?checked.filter(n=>n!==i):[...checked,i],reviewed:false})}/>{r}</label>)}<Button disabled={checked.length!==p.rubric.length} onClick={()=>update(p.id,{reviewed:true})}>{item.reviewed?<><CheckCircle2/> Self-reviewed</>:'Mark lab self-reviewed'}</Button><p>Self-reviewed labs are tracked separately from auto-checked challenges.</p></>:<>
 {showCustom&&<div className="custom"><label>Test call (Python expression)<Input name="custom-expression" autoComplete="off" spellCheck={false} value={customExpr} onChange={e=>setCustomExpr(e.target.value)} placeholder={p.tests[0]?.expr}/></label><label>Expected value (JSON)<Input name="expected-result" autoComplete="off" spellCheck={false} value={customExpected} onChange={e=>setCustomExpected(e.target.value)} placeholder="1"/></label><Button variant="outline" disabled={busy} onClick={()=>run(false,true)}>Run custom test</Button><p>SQL custom calls can use conn.execute(code).fetchall().</p></div>}
 <details className="stdin"><summary>Standard input</summary><textarea name="standard-input" spellCheck={false} aria-label="Standard input" value={stdin} onChange={e=>setStdin(e.target.value)} placeholder="One line per input() call"/></details>
 <div role="status" aria-live="polite" className={'runstatus '+(busy?'running':'')}>{busy&&<span className="spinner"/>}{results.length>0&&results.every(r=>r.passed)&&<svg className="success-check" viewBox="0 0 24 24" aria-hidden="true"><motion.path d="M5 12l4 4L19 6" fill="none" stroke="currentColor" strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}} transition={{duration:motionPaused?0:.3}}/></svg>}{runStatus||'Run the examples, then submit against the full test set.'}</div>
 {!results.length&&!busy&&<div className="emptyconsole"><Terminal/><p>Ready when you are</p><span>Run your code to see results here.</span></div>}
 {results.map((r,i)=><details className={'test '+(r.passed?'pass':'fail')} key={i} open={!r.passed}><summary><span>{r.passed?'✓':'×'}</span>{r.label}<em>{r.passed?'Passed':'Failed'}</em></summary><pre>Call: {r.expression}<br/>Expected: {display(r.expected)}<br/>Actual: {r.error?'Error':display(r.actual)}</pre>{r.error&&<pre className="error">{r.error}</pre>}<div className="raw-output"><h4>Raw return value (Python repr)</h4><pre>{r.raw||'(No return value captured)'}</pre><h4>Printed output (stdout)</h4><pre>{r.stdout||'(No printed output)'}</pre><h4>Standard error (stderr)</h4><pre>{r.stderr||'(No standard error output)'}</pre></div></details>)}<p className="executionnote">Python runs in your browser via <a href="https://pyodide.org/en/0.28.2/usage/index.html" target="_blank" rel="noreferrer">Pyodide</a>. First load needs internet. Execution stops after 10 seconds. These are practice checks, not official exam marks.</p></>}
 {!!item.attempts?.length&&<details className="history"><summary>Submissions ({item.attempts.length})</summary>{item.attempts.map((a,i)=><div className="attempt" key={a.at}><span>{new Date(a.at).toLocaleString()}<br/>{a.passed}/{a.total} passed</span><Button variant="ghost" onClick={()=>download(`${p.id}-attempt-${i+1}.py`,a.code)}>Download</Button></div>)}</details>}
 </div></section></>:view!=='home'&&<motion.section className="contentview">
 {view==='library'&&<><div className="pageintro"><div><h1>A little challenge.<br/><span>A big step forward.</span></h1><p>Find your next problem. Follow your curiosity.</p></div><div className="bigstat">{bank.filter(p=>p.level==='Stretch').length}<span>stretch challenges</span></div></div><div className="library-topics" aria-label="Challenge collections">{['All topics',...topics].map(t=><button key={t} className={topic===t?'active':''} aria-pressed={topic===t} onClick={()=>setTopic(t)}>{t}</button>)}<button aria-pressed={onlySaved} className={onlySaved?'active':''} onClick={()=>setOnlySaved(!onlySaved)}><Bookmark size={15}/> Bookmarks</button></div><div className="filters"><div className="searchbox"><Search size={17}/><Input name="challenge-search" type="search" autoComplete="off" aria-label="Search challenges" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search challenges…"/></div><NativeSelect aria-label="Filter topic" value={topic} onChange={e=>setTopic(e.target.value)}>{['All topics',...topics].map(x=><option key={x}>{x}</option>)}</NativeSelect><NativeSelect aria-label="Filter difficulty" value={level} onChange={e=>setLevel(e.target.value)}>{['All levels','Foundation','Core','Stretch'].map(x=><option key={x}>{x}</option>)}</NativeSelect><NativeSelect aria-label="Filter source" value={source} onChange={e=>setSource(e.target.value)}>{['All sources','LeetCode','W3Schools','HackerRank','Paper','workflow','exercise'].map(x=><option key={x}>{x}</option>)}</NativeSelect></div><div className="listmeta">{filtered.length} challenges {onlySaved&&'· Bookmarks only'}{refFilter&&` · Syllabus ${refFilter}`}<button onClick={()=>{setTopic('All topics');setLevel('All levels');setSource('All sources');setQuery('');setOnlySaved(false);setRefFilter('')}}>Clear filters</button></div><div className="problem-list">{filtered.map(x=><button className="problem-row" key={x.id} onClick={()=>choose(x.id)}><span className={'statusdot '+(progress[x.id]?.solved?'done':'')}>{progress[x.id]?.solved?<Check size={15}/>:String(bank.indexOf(x)+1).padStart(2,'0')}</span><div><strong>{x.title}</strong><span>{x.topic} · {x.source}</span></div><span className={'level '+x.level.toLowerCase()}>{x.level}</span><span className="rowtime">{x.minutes} min</span><ChevronRight size={17}/></button>)}{!filtered.length&&<p className="noresults">No matching challenges. Try a different filter.</p>}</div></>}
 {view==='papers'&&<><div className="pageintro"><div><h1>Sources</h1><p>60 adapted exercises covering H2 Computing practical skills.</p></div><FileText size={42}/></div><Suspense fallback={<EditorSkeleton/>}><PapersPanel onStart={startExam} onOpen={choose}/></Suspense><div className="reference"><h3>How the challenge bank was selected</h3><p>The 2026 syllabus and prelim-paper patterns set the priorities: sorting and searching, pointer structures, validation, files, Python database access, Flask and sockets. Exercises include source credits and syllabus references.</p><p>LeetCode contributes algorithm patterns, W3Schools provides Python and SQL topic practice, and HackerRank offers targeted fundamentals. Prompts are adapted with original reference code and fresh test data.</p><p>This public edition excludes the uploaded original exam PDFs, marking schemes and school resource packs. The 60 adapted challenges and three original local lab packs are included.</p><div className="source-links"><a href="https://leetcode.com/problems/design-circular-queue/" target="_blank" rel="noreferrer">LeetCode · circular queues ↗</a><a href="https://www.w3schools.com/sql/sql_exercises.asp" target="_blank" rel="noreferrer">W3Schools · SQL exercises ↗</a><a href="https://www.hackerrank.com/challenges/find-second-maximum-number-in-a-list/problem" target="_blank" rel="noreferrer">HackerRank · runner-up ↗</a></div></div></>}
 {view==='progress'&&<><div className="pageintro"><div><h1>Your progress</h1><p>Saved in this browser. Export a backup before changing devices or clearing storage.</p></div><BarChart3 size={42}/></div><Suspense fallback={<EditorSkeleton/>}><ProgressPanel highlightedRef={coverageTarget} progress={progress} history={examHistory} labs={labSessions} onTopic={selectFilter} onRef={selectRef}/></Suspense><div className="backup"><h3>Keep a copy of your work</h3><p>Backups include code, recent submissions, bookmarks, lab sessions, exam history and preferences. Import restores matching entries and keeps other challenges.</p><Button onClick={exportWork}><Download/> Export backup</Button><Button variant="outline" onClick={()=>importRef.current?.click()}>Import backup</Button><input type="file" accept="application/json,.json" ref={importRef} hidden onChange={e=>importWork(e.target.files?.[0])}/></div></>}
 {view==='exam'&&<><div className="pageintro"><div><h1>Exam practice</h1><p>Build a balanced paper, target weaker topics or choose your own tasks.</p></div><Timer size={42}/></div>{exam?<div className="examsession"><h2>{exam.title||'Mixed practice'}</h2><div className="clockface">{clock(Math.max(0,Math.ceil((exam.end-(exam.finished?(exam.finishedAt??exam.end):now))/1000)))}</div><p>{exam.finished?'Session ended · Your drafts are saved':'Session in progress · The timer continues if you close this page'}</p>{exam.ids.map((id,i)=>{const x=bank.find(p=>p.id===id)!;return <button className="examtask" key={id} onClick={()=>choose(id)}><span>0{i+1}</span><div><strong>{x.title}</strong><small>{x.topic} · {budgets(exam.ids)[i]} min budget · {x.minutes} min estimate</small></div><ChevronRight/></button>})}<div className="exambuttons">{!exam.finished&&<Button variant="outline" onClick={()=>setConfirmAction('end')}>End session</Button>}<Button onClick={exportWork}>Export your work</Button>{exam.finished&&<Button variant="outline" onClick={()=>setExam(null)}>Set up another session</Button>}</div><p>History counts submissions made in this session. Task budgets divide 180 minutes by the challenge estimates; adapted paper collections may contain fewer or more than four tasks. These are practice checks, not exam marks.</p></div>:<div className="examsetup"><h2>Your four-task practice set</h2><div className="compose-actions"><Button variant="outline" onClick={()=>setMockIds(composePaper(progress))}>Build a balanced paper</Button><Button variant="outline" onClick={()=>setMockIds(composePaper(progress,true))}>Focus on weak topics</Button></div><p>The default set combines file processing, linked structures, databases and a Flask lab. You can choose any four different challenges.</p>{mockIds.map((id,i)=><label key={i}>Task {i+1} · {budgets(mockIds)[i]} min<NativeSelect value={id} onChange={e=>setMockIds(mockIds.map((old,j)=>j===i?e.target.value:old))}>{bank.map(x=><option value={x.id} key={x.id}>{x.title} · {x.topic}</option>)}</NativeSelect></label>)}<Button size="lg" onClick={()=>startExam()}><Play/> Start 3-hour practice</Button><p>Hints and solutions are hidden while the timer runs. Existing drafts are retained. This is a practice session, not an official mock paper or mark scheme.</p></div>}<Suspense fallback={<EditorSkeleton/>}><SessionHistory history={examHistory} labs={labSessions}/></Suspense></>}
 </motion.section>}
 </motion.div></AnimatePresence>
 </div>
 {paletteOpen&&<Suspense fallback={null}><Palette open={paletteOpen} onClose={()=>setPaletteOpen(false)} onChoose={choose} onRef={ref=>{setCoverageTarget(ref);setView('progress')}} onMock={()=>startExam(composePaper(progress))} onTheme={setTheme}/></Suspense>}
 <Dialog open={confirmAction!==null} onOpenChange={open=>{if(!open)setConfirmAction(null)}}><DialogContent className="confirm-dialog"><DialogTitle>{confirmAction==='end'?'End this session?':'Restore the starter code?'}</DialogTitle><DialogDescription>{confirmAction==='end'?'Your code and session results will be saved in practice history.':'This replaces the current draft. Recorded submissions remain available.'}</DialogDescription><div className="confirm-actions"><Button variant="outline" onClick={()=>setConfirmAction(null)}>Cancel</Button><Button onClick={()=>{if(confirmAction==='end'&&exam){stop('Session ended.');setExam({...exam,finished:true,finishedAt:Date.now()})}else if(confirmAction==='reset'){update(p.id,{code:p.starter})}setConfirmAction(null)}}>{confirmAction==='end'?'End and save session':'Restore starter'}</Button></div></DialogContent></Dialog>
 </main></MotionConfig>
}
