import {useEffect} from 'react';
import {useRouteField,navigate} from './routes';
import modules from './reviews.json';
export type Reviews=Record<string,{answers:Record<string,string>;checks:string[]}>;
export default function ReviewModules({value,onChange}:{value:Reviews;onChange:(value:Reviews)=>void}){
 const [target]=useRouteField('module');const [question]=useRouteField('question');
 useEffect(()=>{const el=document.getElementById(question?`review-${target}-${question}`:`review-${target}`);if(el){const parent=el.closest('details');if(parent)parent.open=true;el.scrollIntoView({block:'center'});el.focus()}},[target,question]);
 const unanswered=modules.reduce((n,m)=>n+m.questions.filter(q=>!value[m.id]?.answers[q.id]?.trim()).length,0);
 return <section className="review-modules"><h1>Syllabus review</h1><p>{unanswered} unanswered questions · {modules.reduce((n,m)=>n+m.questions.length,0)} total</p><p>Eight short modules. Write your answer, compare the model answer, then self-review. Notes save on this device and are included in backups. These are not auto-marked.</p>{modules.map(m=>{const entry=value[m.id]||{answers:{},checks:[]};return <details className="reference review-module" key={m.id} id={`review-${m.id}`} tabIndex={-1}><summary><strong>{m.title}</strong><span>{entry.checks.length}/{m.questions.length} self-reviewed · {m.ref}</span></summary>{m.questions.map(q=><section className="review-question" key={q.id} id={`review-${m.id}-${q.id}`} tabIndex={-1}><a href={`#/review?module=${m.id}&question=${q.id}`} onClick={e=>{e.preventDefault();navigate({view:'review',module:m.id,question:q.id})}}>Question {q.id} · Link</a><label htmlFor={`${m.id}-${q.id}`}>{q.prompt}</label><textarea id={`${m.id}-${q.id}`} value={entry.answers[q.id]||''} placeholder="Explain your reasoning…" onChange={e=>onChange({...value,[m.id]:{answers:{...entry.answers,[q.id]:e.target.value},checks:entry.checks.filter(id=>id!==q.id)}})}/><details><summary>Compare model answer</summary><p>{q.answer}</p></details><label className="checkrow"><input type="checkbox" checked={entry.checks.includes(q.id)} onChange={e=>onChange({...value,[m.id]:{...entry,checks:e.target.checked?[...entry.checks,q.id]:entry.checks.filter(id=>id!==q.id)}})}/>{q.check}</label></section>)}{m.source&&<a href={m.source} target="_blank" rel="noreferrer">PDPC: data protection obligations ↗</a>}</details>})}</section>
}
