import bank from './problems.json';
export type ProblemKind='python'|'sql'|'mongo'|'lab';
export type Problem=(typeof bank)[number];
export type Attempt={at:string;passed:number;total:number;code:string;sessionId?:string};
export type Progress={code?:string;solved?:boolean;reviewed?:boolean;bookmarked?:boolean;checks?:number[];attempts?:Attempt[];notes?:string};
export type Exam={end:number;ids:string[];finished:boolean;id?:string;startedAt?:number;finishedAt?:number;title?:string};
export type TaskOutcome={id:string;passed:number;total:number;reviewed:boolean};
export type ExamRecord={id:string;startedAt:number;endedAt:number;title:string;tasks:TaskOutcome[]};
export type LabSession={id:string;problemId:string;startedAt:number;endedAt?:number;notes:string;checks:number[];examId?:string};
export type Saved={version:1;progress:Record<string,Progress>;exam:Exam|null;selected:string;examHistory?:ExamRecord[];labSessions?:LabSession[];examDate?:string;theme?:'system'|'light'|'dark'};
export const topics=['Algorithms','Data structures','Python & files','Databases','Web & networks'];
export const syllabusSource='https://www.seab.gov.sg/files/A%20Level%20Syllabus%20Sch%20Cddts/2026/9569_y26_sy.pdf';
const sections:Record<string,[string,string[]]>={
 '1.1':['Algorithmic representation',['Pseudocode and flowcharts','Flowchart symbols','Combined control structures','Decision tables','Modular decomposition']],
 '1.2':['Fundamental algorithms',['Implement sorting','Explain sorting','Implement searching','Explain searching','Algorithm efficiency']],
 '1.3':['Data structures',['Static memory','Dynamic memory','Stacks and queues','Free space lists','Linked lists','Binary trees','Tree traversals']],
 '2.1':['Coding standards',['Indentation and whitespace','Meaningful names','Program comments']],
 '2.2':['Programming constructs',['Types and arrays','Library functions','Control flow','Functions and procedures','Recursion','Trace execution','Recursion stacks']],
 '2.3':['Algorithm implementation',['Sort programs','Search programs','Data structure programs','Text files']],
 '2.4':['Validation and testing',['Validation versus verification','Validation techniques','Find and fix errors','Design test cases']],
 '2.5':['Object-oriented programming',['Classes and objects','Encapsulation','Inheritance','Polymorphism','Class diagrams']],
 '3.1':['Data representation',['Binary and hexadecimal','Number-base conversion']],
 '3.2':['Character encoding',['Unicode','ASCII in programs']],
 '3.3':['Databases and data management',['Tables, records and fields','Database keys','Redundancy and dependencies','Third normal form','Entity relationships','NoSQL design','SQL and NoSQL applications','Database programming','Data privacy and integrity','Protecting data','Backup versus archive','Version control','Personal data protection']],
 '3.4':['Computing in society',['Professional ethics','Social and economic impact','Technology issues']],
 '4.1':['Computer networks',['Network types and internet','IP addresses and DNS','Communication protocols','Packet switching','Client-server architecture','Socket programming']],
 '4.2':['Web applications',['Web versus native apps','Usability principles','Build web applications','Local-server testing']],
 '4.3':['Network security',['Malware and denial of service','Firewalls and intrusion detection','Encryption and authentication']],
};
export const syllabus=Object.entries(sections).flatMap(([section,[group,titles]])=>titles.map((title,i)=>({code:`${section}.${i+1}`,group,title})));
export function references(ref:string):string[]{const expanded=ref.replace(/(\d\.\d\.)(\d+)[–-]\d\.\d\.(\d+)/g,(_,prefix,a,b)=>Array.from({length:+b-+a+1},(_,i)=>prefix+(+a+i)).join(' / '));return expanded.match(/\d\.\d\.\d+/g)||[]}
export function topicStats(progress:Record<string,Progress>){return topics.map(topic=>{const problems=bank.filter(p=>p.topic===topic);const attempts=problems.flatMap(p=>progress[p.id]?.attempts||[]);const passed=attempts.filter(a=>a.passed===a.total).length;return {topic,problems,attempts:attempts.length,passed,rate:attempts.length?Math.round(passed/attempts.length*100):null,solved:problems.filter(p=>progress[p.id]?.solved).length,reviewed:problems.filter(p=>p.kind==='lab'&&progress[p.id]?.reviewed).length}})}
export function composePaper(progress:Record<string,Progress>,weak=false,random=Math.random){const stats=topicStats(progress);const selected:Problem[]=[];for(const group of [['Python & files'],['Algorithms','Data structures'],['Databases'],['Web & networks']]){let pool=bank.filter(p=>group.includes(p.topic));if(weak){const weakest=stats.filter(s=>group.includes(s.topic)).sort((a,b)=>(a.rate??-1)-(b.rate??-1))[0];pool=pool.filter(p=>p.topic===weakest.topic);const unsolved=pool.filter(p=>!progress[p.id]?.solved&&!progress[p.id]?.reviewed);if(unsolved.length)pool=unsolved}const challenging=pool.filter(p=>p.level!=='Foundation');if(challenging.length)pool=challenging;selected.push(pool[Math.min(pool.length-1,Math.floor(random()*pool.length))])}return selected.map(p=>p.id)}
export function budgets(ids:string[]){if(!ids.length)return [];const estimates=ids.map(id=>bank.find(p=>p.id===id)?.minutes||30);const sum=estimates.reduce((a,b)=>a+b,0);const result=estimates.map(n=>Math.floor(n/sum*180));for(let i=0;result.reduce((a,b)=>a+b,0)<180;i++)result[i%result.length]++;return result}
export function paperGroups(){const groups:Record<string,Problem[]>={};for(const p of bank){for(const name of new Set(p.source.match(/(?:ACJC|ASRJC|DHS|HCI|JPJC|NJC|NYJC|RI|RVHS|VJC) 20\d{2}/g)||[])){(groups[name]??=[]).push(p)}}return Object.entries(groups).sort(([a],[b])=>a.localeCompare(b))}
export function finishRecord(exam:Exam,progress:Record<string,Progress>,labs:LabSession[]):ExamRecord{const startedAt=exam.startedAt??exam.end-10800000;const endedAt=Math.min(exam.finishedAt??exam.end,exam.end);return {id:exam.id??String(exam.end),startedAt,endedAt,title:exam.title||'Mixed practice',tasks:exam.ids.map(id=>{const p=bank.find(p=>p.id===id)!;const a=(progress[id]?.attempts||[]).find(a=>exam.id?a.sessionId===exam.id:Date.parse(a.at)>=startedAt&&Date.parse(a.at)<=endedAt);return {id,passed:a?.passed??0,total:p.tests.length,reviewed:labs.some(l=>l.problemId===id&&l.examId===exam.id&&l.startedAt>=startedAt&&l.endedAt&&l.endedAt<=endedAt&&l.checks.length===p.rubric.length)}})}}
export function daysUntil(date:string,now=new Date()){if(!date)return null;const target=new Date(date+'T00:00:00');if(!Number.isFinite(+target))return null;return Math.round((Date.UTC(target.getFullYear(),target.getMonth(),target.getDate())-Date.UTC(now.getFullYear(),now.getMonth(),now.getDate()))/86400000)}
const known=(id:unknown):id is string=>typeof id==='string'&&bank.some(p=>p.id===id);
const finite=(x:unknown):x is number=>typeof x==='number'&&Number.isFinite(x)&&x>=0;
export function validateSaved(input:unknown):Saved{
 const d=input as Saved;if(!d||d.version!==1||!d.progress||typeof d.progress!=='object'||Array.isArray(d.progress))throw Error('Invalid backup');
 const progress:Record<string,Progress>={};for(const [id,p] of Object.entries(d.progress)){if(!known(id))continue;if(!p||typeof p!=='object'||p.code!==undefined&&typeof p.code!=='string'||p.notes!==undefined&&typeof p.notes!=='string')throw Error('Invalid draft');for(const flag of ['solved','reviewed','bookmarked'] as const)if(p[flag]!==undefined&&typeof p[flag]!=='boolean')throw Error('Invalid progress flag');const max=bank.find(x=>x.id===id)!.rubric.length;if(p.checks&&(!Array.isArray(p.checks)||!p.checks.every(n=>Number.isInteger(n)&&n>=0&&n<max)))throw Error('Invalid checklist');if(p.attempts&&(!Array.isArray(p.attempts)||!p.attempts.every(a=>typeof a.code==='string'&&Number.isFinite(Date.parse(a.at))&&finite(a.passed)&&finite(a.total)&&a.passed<=a.total&&(!a.sessionId||typeof a.sessionId==='string'))))throw Error('Invalid attempts');progress[id]={...p,attempts:p.attempts?.slice(0,20),checks:[...new Set(p.checks)]}}
 if(d.exam&&(!Array.isArray(d.exam.ids)||!d.exam.ids.length||!d.exam.ids.every(known)||new Set(d.exam.ids).size!==d.exam.ids.length||!finite(d.exam.end)||typeof d.exam.finished!=='boolean'||d.exam.id!==undefined&&typeof d.exam.id!=='string'||d.exam.startedAt!==undefined&&!finite(d.exam.startedAt)||d.exam.finishedAt!==undefined&&!finite(d.exam.finishedAt)||d.exam.title!==undefined&&typeof d.exam.title!=='string'))throw Error('Invalid session');
 if(d.examHistory&&(!Array.isArray(d.examHistory)||!d.examHistory.every(e=>typeof e.id==='string'&&typeof e.title==='string'&&finite(e.startedAt)&&finite(e.endedAt)&&e.endedAt>=e.startedAt&&Array.isArray(e.tasks)&&e.tasks.every(t=>known(t.id)&&finite(t.passed)&&finite(t.total)&&t.passed<=t.total&&typeof t.reviewed==='boolean'))))throw Error('Invalid history');
 if(d.labSessions&&(!Array.isArray(d.labSessions)||!d.labSessions.every(l=>typeof l.id==='string'&&known(l.problemId)&&bank.find(p=>p.id===l.problemId)?.kind==='lab'&&finite(l.startedAt)&&(!l.endedAt||finite(l.endedAt)&&l.endedAt>=l.startedAt)&&typeof l.notes==='string'&&Array.isArray(l.checks)&&new Set(l.checks).size===l.checks.length&&l.checks.every(n=>Number.isInteger(n)&&n>=0&&n<bank.find(p=>p.id===l.problemId)!.rubric.length))))throw Error('Invalid labs');
 if(d.examDate&&(!/^\d{4}-\d{2}-\d{2}$/.test(d.examDate)||!Number.isFinite(Date.parse(d.examDate))))throw Error('Invalid date');
 return {...d,progress,selected:known(d.selected)?d.selected:bank[0].id,exam:d.exam??null,examHistory:d.examHistory||[],labSessions:d.labSessions||[],examDate:d.examDate||'',theme:['light','dark'].includes(d.theme||'')?d.theme:'system'};
}
