import reviewModules from './reviews.json';
import type {Reviews} from './ReviewModules';
import {useEffect,useState} from 'react';
import {AreaChart,Area,CartesianGrid,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import {Button} from '@/components/ui/button';
import {CheckCircle2,ChevronRight,Play,Square,BookOpen} from 'lucide-react';
import bank from './problems.json';
import {syllabus,syllabusSource,references,topicStats,paperGroups,type Progress,type ExamRecord,type LabSession,type Problem} from './study';
export function SessionHistory({history,labs}:{history:ExamRecord[];labs:LabSession[]}){return <section className="history-panel"><h2>Practice history</h2><p>Session-only test results, not official marks. Lab reviews are recorded separately.</p>{history.length>1&&<div className="attempt-chart" role="img" aria-label="Session test pass percentages over time; exact scores are listed below"><ResponsiveContainer width="100%" height={160}><AreaChart data={[...history].reverse().map(e=>{const total=e.tasks.reduce((n,t)=>n+t.total,0);return {date:new Date(e.startedAt).toLocaleDateString(),rate:total?Math.round(e.tasks.reduce((n,t)=>n+t.passed,0)/total*100):null}})}><XAxis dataKey="date" tick={{fill:'var(--secondary)',fontSize:11}}/><YAxis domain={[0,100]} tick={{fill:'var(--secondary)',fontSize:11}}/><Tooltip contentStyle={{background:'var(--surface)',borderColor:'var(--border)',color:'var(--foreground)'}}/><Area dataKey="rate" name="Checks passed (%)" stroke="var(--primary)" fill="var(--selection)" isAnimationActive={false}/></AreaChart></ResponsiveContainer></div>}{!history.length&&!labs.some(l=>l.endedAt)?<div className="designed-empty"><BookOpen/><strong>Your next session starts the story.</strong><span>Finish an exam or lab session to see it here.</span></div>:<div className="session-list">{history.map(e=>{const passed=e.tasks.reduce((n,t)=>n+t.passed,0),total=e.tasks.reduce((n,t)=>n+t.total,0);return <details key={e.id}><summary><span><strong>{e.title}</strong><small>{new Date(e.startedAt).toLocaleString()} · {Math.ceil((e.endedAt-e.startedAt)/60000)} min</small></span><span>{passed}/{total} checks · {e.tasks.filter(t=>t.reviewed).length} labs reviewed</span></summary><ul>{e.tasks.map(t=><li key={t.id}>{bank.find(p=>p.id===t.id)?.title}: {t.total?`${t.passed}/${t.total} checks`:t.reviewed?'Self-reviewed':'Not self-reviewed'}</li>)}</ul></details>})}{labs.filter(l=>l.endedAt).map(l=><details key={l.id}><summary><span><strong>{bank.find(p=>p.id===l.problemId)?.title}</strong><small>{new Date(l.startedAt).toLocaleString()} · {Math.ceil((l.endedAt!-l.startedAt)/60000)} min</small></span><span>{l.checks.length}/{bank.find(p=>p.id===l.problemId)?.rubric.length} criteria reviewed</span></summary><p className="lab-notes">{l.notes||'No session notes.'}</p></details>)}</div>}</section>}
export function ProgressPanel({progress,history,labs,onTopic,onRef,highlightedRef,reviews,onReviews}:{progress:Record<string,Progress>;history:ExamRecord[];labs:LabSession[];reviews:Reviews;onReviews:()=>void;highlightedRef?:string;onTopic:(topic:string)=>void;onRef:(ref:string)=>void}){
 useEffect(()=>{if(highlightedRef)document.getElementById(`coverage-${highlightedRef}`)?.scrollIntoView({block:'center'})},[highlightedRef]);
 const stats=topicStats(progress);const attempts=Object.values(progress).flatMap(p=>p.attempts||[]);const days=new Map<string,{day:string;attempts:number;passed:number}>();for(const a of attempts){const d=new Date(a.at);const day=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const v=days.get(day)||{day,attempts:0,passed:0};v.attempts++;if(a.passed===a.total)v.passed++;days.set(day,v)}const chart=[...days.values()].sort((a,b)=>a.day.localeCompare(b.day));
 return <><div className="topic-rings">{stats.map(s=>{const auto=s.problems.filter(p=>p.kind!=='lab').length;const completed=s.solved+s.reviewed;return <button key={s.topic} className="topic-ring-card" onClick={()=>onTopic(s.topic)}><div className="progress-orbit"><svg viewBox="0 0 200 200" aria-hidden="true"><circle cx="100" cy="100" r="84"/><circle cx="100" cy="100" r="84" className="orbit-fill" strokeDasharray={`${completed/s.problems.length*528} 528`}/></svg><div><strong>{completed}<span>/{s.problems.length}</span></strong></div></div><strong>{s.topic}</strong><span>{auto?`${s.solved} auto-checked · ${s.reviewed} labs`:`${s.reviewed} labs self-reviewed`}</span></button>})}</div>
 <section className="insight-panel"><h2>Where to practise next</h2><p>Pass rate means submissions passing every check. Unattempted topics have no rate yet.</p>{[...stats].sort((a,b)=>(a.rate??-1)-(b.rate??-1)).map(s=><button className="weak-topic" key={s.topic} onClick={()=>onTopic(s.topic)}><span><strong>{s.topic}</strong><small>{s.attempts} retained submissions</small></span><span>{s.rate===null?'Not attempted':`${s.rate}% pass rate`}</span><ChevronRight size={17}/></button>)}</section>
 <section className="insight-panel"><h2>Your practice rhythm</h2><p>Retained submissions by day. Each challenge keeps its latest 20 submissions.</p>{chart.length?<><div className="attempt-chart" role="img" aria-label="Daily submissions and fully passing submissions; exact values in the table below"><ResponsiveContainer width="100%" height={220}><AreaChart data={chart} margin={{top:15,right:20,bottom:0,left:-20}}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="day" tick={{fill:'var(--secondary)',fontSize:11}} tickFormatter={d=>new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'})}/><YAxis allowDecimals={false} tick={{fill:'var(--secondary)',fontSize:11}}/><Tooltip contentStyle={{background:'var(--surface)',borderColor:'var(--border)',color:'var(--foreground)'}}/><Area type="monotone" dataKey="attempts" name="Submissions" stroke="var(--primary)" fill="var(--selection)" isAnimationActive={false}/><Area type="monotone" dataKey="passed" name="Fully passed" stroke="var(--success)" fill="var(--success-bg)" isAnimationActive={false}/></AreaChart></ResponsiveContainer></div><details><summary>View daily counts</summary><table className="data-table"><thead><tr><th>Date</th><th>Submissions</th><th>Fully passed</th></tr></thead><tbody>{chart.map(d=><tr key={d.day}><td>{d.day}</td><td>{d.attempts}</td><td>{d.passed}</td></tr>)}</tbody></table></details></>:<div className="designed-empty"><CheckCircle2/><strong>Make your first submission.</strong><span>Running examples helps you debug. Submitting records your progress.</span></div>}</section>
 <section className="coverage-panel" id="syllabus-coverage"><h2>Syllabus coverage</h2><p>All {syllabus.length} points from the <a href={syllabusSource} target="_blank" rel="noreferrer">2026 syllabus</a>. Mappings include practical exercises and theory reviews. Completion is practice evidence, not proof of mastery. Theory answers and local labs are self-reviewed.</p><div className="coverage-legend"><span>Untouched</span><span>In progress</span><span>Complete / self-reviewed</span><span>No mapped exercise</span></div>{[...new Set(syllabus.map(s=>s.group))].map(group=><details className="coverage-group" key={group} open><summary>{group}</summary><div className="coverage-grid">{syllabus.filter(s=>s.group===group).map(s=>{const items=bank.filter(p=>references(p.ref).includes(s.code));const complete=items.filter(p=>p.kind==='lab'?progress[p.id]?.reviewed:progress[p.id]?.solved).length;const attempted=items.some(p=>progress[p.id]?.attempts?.length||progress[p.id]?.checks?.length||progress[p.id]?.code!==undefined);const theory=reviewModules.filter(m=>references(m.ref).includes(s.code));const reviewed=theory.filter(m=>m.questions.every(q=>reviews[m.id]?.checks.includes(q.id))).length;const status=!items.length&&theory.length?(reviewed===theory.length?'complete':theory.some(m=>Object.keys(reviews[m.id]?.answers||{}).length)?'attempted':'untouched'):!items.length?'unmapped':complete===items.length?'complete':attempted||complete?'attempted':'untouched';return <button id={`coverage-${s.code}`} data-highlighted={highlightedRef===s.code} disabled={!items.length&&!theory.length} key={s.code} className={`coverage-point ${status}`} onClick={()=>items.length?onRef(s.code):onReviews()}><strong>{s.code} · {s.title}</strong><small>{!items.length?(theory.length?`${reviewed}/${theory.length} theory modules self-reviewed`:'No mapped exercise'):`${complete}/${items.length} complete · ${status==='complete'?'Complete / self-reviewed':status==='attempted'?'In progress':'Untouched'}`}</small></button>})}</div></details>)}</section>
 <SessionHistory history={history} labs={labs}/></>
}
export function PapersPanel({onStart,onOpen}:{onStart:(ids:string[],name:string)=>void;onOpen:(id:string)=>void}){return <section className="paper-collections"><h2>Practise by source paper</h2><p>Adapted challenge collections, not complete reproductions or official mock papers. Original school files are not hosted here.</p><div className="paper-grid">{paperGroups().map(([name,items])=><article key={name}><h3>{name}</h3><p>{items.length} adapted challenges · {items.reduce((n,p)=>n+p.minutes,0)} min of estimated work</p><Button onClick={()=>onStart(items.map(p=>p.id),`${name} · adapted collection`)}>Practise collection</Button><details><summary>Included challenges</summary>{items.map(p=><button className="text-link" key={p.id} onClick={()=>onOpen(p.id)}>{p.title}<ChevronRight size={14}/></button>)}</details></article>)}</div></section>}
export function LabPractice({problem,sessions,onChange,onReview,examId}:{problem:Problem;sessions:LabSession[];onChange:(next:LabSession[])=>void;onReview:(checks:number[],notes:string)=>void;examId?:string}){
 const [now,setNow]=useState(Date.now());const [step,setStep]=useState(0);const session=sessions.find(s=>s.problemId===problem.id&&!s.endedAt);useEffect(()=>{if(!session)return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[session?.id]);const revise=(patch:Partial<LabSession>)=>{if(session)onChange(sessions.map(s=>s.id===session.id?{...s,...patch}:s))};
 return <div className="lab-session"><h3>Guided lab session</h3>{!session?<><p>Run the project on your computer, then walk through the rubric here. The timer and notes are saved on this device.</p><Button onClick={()=>{onChange([{id:crypto.randomUUID(),problemId:problem.id,startedAt:Date.now(),notes:'',checks:[],examId},...sessions]);setStep(0);setNow(Date.now())}}><Play/> Start lab session</Button></>:<><div className="lab-timer"><strong>{Math.floor(Math.max(0,now-session.startedAt)/60000)} min</strong><span>Criterion {step+1} of {problem.rubric.length}</span></div><p className="rubric-step">{problem.rubric[step]}</p><label className="checkrow"><input type="checkbox" checked={session.checks.includes(step)} onChange={e=>revise({checks:e.target.checked?[...new Set([...session.checks,step])]:session.checks.filter(n=>n!==step)})}/> I verified this locally</label><div className="lab-controls"><Button variant="outline" disabled={step===0} onClick={()=>setStep(step-1)}>Previous</Button><Button variant="outline" disabled={step===problem.rubric.length-1} onClick={()=>setStep(step+1)}>Next criterion</Button></div><label className="notes-label">Session notes<textarea value={session.notes} onChange={e=>revise({notes:e.target.value})} placeholder="What worked? What needs another try?"/></label><Button onClick={()=>{revise({endedAt:Date.now()});onReview(session.checks,session.notes)}}><Square/> Finish and save session</Button><p>{session.checks.length}/{problem.rubric.length} criteria verified. Completing all criteria marks this lab self-reviewed.</p></>}</div>
}
