import {useCallback,useEffect,useRef,useState} from 'react';
import {DeviceStore,ConflictError} from './device-store';
import {validateSaved,type Saved} from './study';
export function useDeviceSave(snapshot:Saved,apply:(value:Saved)=>void){
 const [loaded,setLoaded]=useState(false),[status,setStatus]=useState<'loading'|'saved'|'saving'|'failed'|'conflict'|'paused'>('loading');
 const [message,setMessage]=useState('');const store=useRef<DeviceStore|null>(null);const channel=useRef<BroadcastChannel|null>(null);const latest=useRef(snapshot);latest.current=snapshot;const applyRef=useRef(apply);applyRef.current=apply;
 const lastSaved=useRef<Saved|null>(null);const unchanged=(value:Saved)=>lastSaved.current!==null&&(Object.keys(value) as (keyof Saved)[]).every(k=>value[k]===lastSaved.current![k]);
 const exitAllowed=useRef(false);const ready=useRef(false);const paused=useRef(false);const chain=useRef<Promise<unknown>>(Promise.resolve());const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 const save=useCallback(async()=>{if(!ready.current||!store.current||paused.current)return false;clearTimeout(timer.current);const value=latest.current;if(unchanged(value)){setStatus('saved');return true}setStatus('saving');
  const work=chain.current.then(async()=>{if(paused.current)return false;try{await store.current!.save(value);lastSaved.current=value;setStatus(value===latest.current?'saved':'saving');channel.current?.postMessage({revision:store.current!.revision});return value===latest.current}catch(e){paused.current=e instanceof ConflictError;setStatus(paused.current?'conflict':'failed');setMessage(paused.current?'Another tab has newer saved work. Export this tab before choosing which version to keep.':'Device save failed. Export a backup to keep your work.');return false}});chain.current=work;return work;
 },[]);
 useEffect(()=>{let active=true;DeviceStore.open(validateSaved).then(async db=>{if(!active){db.close();return}store.current=db;try{const result=await db.load(()=>localStorage.getItem('practical9569.v1'));if(!active)return;if(result.value){lastSaved.current=result.value;applyRef.current(result.value);}if(result.recovered)setMessage('Recovered the previous readable snapshot. Export a backup now.');ready.current=true;setStatus('saved')}catch{paused.current=true;setStatus('paused');setMessage('Saved data could not be read. Original data is preserved; import a valid backup to resume saving.')}if(active)setLoaded(true)}).catch(()=>{if(active){paused.current=true;setStatus('failed');setMessage('Device storage is unavailable. Keep this tab open and export your work.');setLoaded(true)}});
  if(typeof BroadcastChannel!=='undefined'){const c=new BroadcastChannel('practical9569.saves');channel.current=c;c.onmessage=e=>{if(store.current&&e.data.revision>store.current.revision){paused.current=true;setStatus('conflict');setMessage('Another tab saved newer work. Saving here is paused until you choose a version.')}}}
  return()=>{active=false;clearTimeout(timer.current);channel.current?.close();store.current?.close()};
 },[]);
 useEffect(()=>{if(!loaded||paused.current)return;if(unchanged(snapshot)){setStatus('saved');return}setStatus('saving');clearTimeout(timer.current);timer.current=setTimeout(()=>{void save()},250);return()=>clearTimeout(timer.current)},[snapshot,loaded,save]);
 useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(!exitAllowed.current&&(!ready.current||paused.current||!unchanged(latest.current))){e.preventDefault();e.returnValue=''}};const hide=()=>{if(document.visibilityState==='hidden')void save()};window.addEventListener('beforeunload',leave);document.addEventListener('visibilitychange',hide);return()=>{window.removeEventListener('beforeunload',leave);document.removeEventListener('visibilitychange',hide)}},[status,save]);
 const resolve=async(keepThisTab:boolean)=>{if(!store.current)return;await chain.current;const result=await store.current.load(()=>null);paused.current=false;if(!keepThisTab&&result.value){lastSaved.current=result.value;applyRef.current(result.value);}setMessage('');setStatus('saved');if(keepThisTab)await save()};
 return {loaded,status,message,save,resolve,prepareExit:()=>{exitAllowed.current=true},original:async()=>store.current?JSON.stringify(await store.current.record(),null,2):localStorage.getItem('practical9569.v1')||'',resume:()=>{if(!store.current){setStatus('failed');return}ready.current=true;paused.current=false;setStatus('saved')},previous:async()=>{if(!store.current)throw Error('Device storage unavailable');return store.current.previous()}};
}
