import json,zipfile
from pathlib import Path
root=Path('content/expansion/labs')
metadata=[
('bookings-portal','Searchable bookings portal','4.2.2–4.2.4 / 3.3.8',55,'Implement create_app(database). The SQLite database contains Customer, Event and Booking tables. Seed two customers and two events only if absent. GET / accepts optional exact day/category filters and displays joined bookings, including an empty-results message. POST / validates customer/event IDs and quantity 1–8, inserts with parameters and redirects. Reject duplicates or invalid input with HTTP 400 without a write. Build and inspect the labelled HTML forms and results table.', ['Filter by category and real ISO date; include an empty-results view.','Validate and parameterise every booking insert; verify persistence after restarting.','Run test_lab.py and review semantic labels, table headings and keyboard access.'], 'def create_app(database="bookings.db"):\n    # Create schema, routes and templates.\n    raise NotImplementedError\n'),
('photo-catalogue','Photo catalogue upload','4.2.3–4.2.4 / 2.4.2',45,'Implement create_app(database, upload_dir). GET / lists saved image titles and images. POST / accepts title and photo; require a nonempty title and a valid PNG/JPEG image no larger than the 2 MiB request limit. Use a generated filename, save the image and its SQLite row, and redirect. Validate image content, not just its extension. Delete the saved file if the database write fails. GET /photos/<name> serves existing uploads and returns 404 for missing files. Use the supplied tests and inspect the rendered gallery.', ['Reject missing/corrupt uploads before writing files or rows.','Generate distinct safe filenames even for identical original names; serve images through a safe directory route.','Verify cleanup on database failure, persistent rows and descriptive image alt text.'], 'def create_app(database="photos.db", upload_dir="uploads"):\n    raise NotImplementedError\n'),
('quiz-server','Implement the missing quiz server','4.1.5–4.1.6 / 2.5.1–2.5.2',50,'Use the supplied client.py and protocol to implement an iterative quiz server in starter.py. Each connection sends a JSON username line, answers two questions and receives its own score. Define Question and QuizSession classes and serve(listener, max_clients=None). Preserve message boundaries across recv chunks. A partial/invalid/disconnected client must not prevent the next connection. The reference questions and exact protocol are documented in README.md; test on loopback only.', ['Implement Question.correct and per-client QuizSession state.','Support newline framing with a 4096-byte message limit and a timeout.','Serve multiple connections sequentially; recover from a client disconnect and keep scores isolated.'], 'class Question:\n    pass\n\nclass QuizSession:\n    pass\n\ndef serve(listener, max_clients=None):\n    raise NotImplementedError\n'),
('game-client','Implement the missing game client','4.1.5–4.1.6 / 2.2.3',45,'Use the supplied deterministic server.py. Implement play(connection, moves), reading newline-delimited JSON messages: info is informational; turn/retry requests the next [row,col] move; done returns its result string. Unknown message types or exhausted moves raise ValueError. EOF, oversized or incomplete lines before done raise ConnectionError. Support split/coalesced messages, invalid-move retry and normal termination. Start the supplied server and run your client over loopback.', ['Read one complete JSON message at a time without losing coalesced data.','Send one move for each turn or retry, and ignore informational messages.','Pass disconnect/framing checks and complete a real client/server session.'], 'def play(connection, moves):\n    raise NotImplementedError\n'),
('lost-property','Document-backed lost property','3.3.8 / 2.4.2 / 4.2.2–4.2.4',55,'Implement create_app(collection=None) with Flask and real PyMongo. POST / validates a title, an exact ISO calendar date and category Books/Clothing/Other, then stores an unclaimed report with a unique generated report_id. GET / supports optional day/category filters. POST /claim/<report_id> marks exactly one matching report claimed, or returns 404. Reject bad input with HTTP 400 without writing. Use a dedicated local MongoDB database and the real-server integration tests in the pack.', ['Validate real calendar dates and controlled categories; reject bad input without writes.','Create a unique report_id index, filter documents and update one selected report.','Run integration tests against real MongoDB and inspect the labelled web forms.'], 'def create_app(collection=None):\n    raise NotImplementedError\n')]
bank=json.loads(Path('app/problems.json').read_text());ids={x[0] for x in metadata};bank=[p for p in bank if p['id'] not in ids]
style='body{font:17px system-ui;background:#f5f5f7;color:#202024;margin:0}main{max-width:900px;margin:40px auto;padding:24px}label{display:block;margin:16px 0}input,select,button{font:inherit;padding:9px}table{border-collapse:collapse;width:100%;margin:24px 0}td,th{padding:12px;text-align:left;border-bottom:1px solid #ccc}img{max-width:100%;height:auto}:focus-visible{outline:3px solid #0065cf;outline-offset:3px}'
for id,title,ref,minutes,desc,rubric,starter in metadata:
 folder=root/id;(folder/'starter.py').write_text(starter)
 web=id in ['bookings-portal','photo-catalogue','lost-property']
 requirements='Flask>=3.1,<4\n' if web else ''
 if id=='photo-catalogue':requirements+='Pillow>=11,<13\n'
 if id=='lost-property':requirements+='pymongo>=4.10,<5\n'
 (folder/'requirements.txt').write_text(requirements)
 if web:
  (folder/'static').mkdir(exist_ok=True);(folder/'static/style.css').write_text(style)
 commands='python -m unittest -v test_lab.py'
 run='python solution.py (reference only); add a main entry point to starter.py to run your implementation.'
 if id=='quiz-server':run='Terminal 1: python solution.py (or your server entry point). Terminal 2: python client.py.'
 if id=='game-client':run='Terminal 1: python server.py. Terminal 2: python solution.py (or your client entry point).'
 extra=''
 if id=='quiz-server':extra='''\n## Exact quiz protocol\nUTF-8 JSON, one object plus newline per message, maximum 4096 bytes including newline. First client message: {"username":"Ari"}. Server asks {"type":"question","number":1,"text":"2 + 3? A: 4, B: 5"}; client replies {"answer":"B"}. Question 2 text: "FIFO structure? A: queue, B: stack"; correct answer A. Trim and uppercase answers. Finally send {"type":"result","username":"Ari","score":2}. Only the client that answered correctly gets that score. Timeout each connection after 3 seconds of inactivity. Close malformed clients and keep accepting the next client. max_clients is provided for tests; None means continue.\n'''
 if id=='game-client':extra='''\n## Protocol\nRead each UTF-8 JSON line up to 4096 bytes, including newline. On {"type":"info",...}, keep reading. On turn or retry send {"row":row,"col":col} from the next move. On {"type":"done","result":"win"} return "win". The server treats row/col outside 0–1 as invalid; (1,1) wins. Use a connection timeout in your client entry point.\n'''
 if id=='lost-property':extra='''\n## Real MongoDB\nStart your installed MongoDB server locally. Default URI: mongodb://127.0.0.1:27017; override with MONGO_URI. The reference app uses practical_lost_property.reports. Tests use a newly generated practical_test_<uuid> database and delete only that test database afterwards. Tests deliberately fail if MongoDB is unavailable; they do not silently substitute an emulator.\n'''
 (folder/'README.md').write_text(f'''# {title}\n\nSyllabus: {ref}. Estimated {minutes} minutes. Original synthetic practice project.\n\n{desc}\n\n## Work in this order\n1. Read this contract and test_lab.py; implement starter.py.\n2. Review/edit the supplied HTML and CSS where present.\n3. Run tests, then inspect the real application or network session.\n4. Record your own normal, abnormal and boundary tests.\n5. Compare with solution.py only after attempting the task.\n\n## Setup and checks\nUse Python 3.10 or newer in a virtual environment.\n\n```sh\npython -m venv .venv\n# macOS/Linux: source .venv/bin/activate\n# Windows: .venv\\Scripts\\activate\npython -m pip install -r requirements.txt\n{commands}\n```\n\nTests load starter.py by default. To check the reference instead, set LAB_MODULE=solution (macOS/Linux: `LAB_MODULE=solution python -m unittest -v test_lab.py`; PowerShell: `$env:LAB_MODULE="solution"` then run the test command). Test failure for the unfinished starter is expected.\n\n## Run manually\n{run}\n\n{extra}\n## Review checklist\n'''+''.join(f'- [ ] {r}\n' for r in rubric)+'''\nThese local learning apps do not include production authentication. Use fictional data and loopback addresses. The tests exercise behaviour; manually review your code structure and rendered pages too.\n\nReferences: [Flask testing](https://flask.palletsprojects.com/en/stable/testing/), [Flask uploads](https://flask.palletsprojects.com/en/stable/patterns/fileuploads/), [PyMongo connections](https://www.mongodb.com/docs/languages/python/pymongo-driver/current/connect/).\n''')
 zip_path=Path('public/labs')/(id+'.zip')
 with zipfile.ZipFile(zip_path,'w',zipfile.ZIP_DEFLATED) as z:
  for f in sorted(folder.rglob('*')):
   if f.is_file() and '__pycache__' not in f.parts and f.suffix!='.pyc':
    info=zipfile.ZipInfo(str(f.relative_to(folder)));info.compress_type=zipfile.ZIP_DEFLATED;z.writestr(info,f.read_bytes())
 bank.append(dict(id=id,title=title,topic='Web & networks',level='Stretch',minutes=minutes,ref=ref,description=desc,starter=starter,solution=(folder/'solution.py').read_text(),tests=[],hints=['Read the protocol or route contract before coding.','Use the test harness, then verify the full local workflow.'],setup='',files={},kind='lab',rubric=rubric,source='Original syllabus expansion',sourceUrl=''))
Path('app/problems.json').write_text(json.dumps(bank,ensure_ascii=False,indent=2)+'\n')
print('Built 5 reproducible lab packs; total challenges:',len(bank))
