import {memo,useId} from 'react';
import {AnimatePresence,motion} from 'motion/react';
import type {Algorithm,Step} from './engine';
function stateName(id:string,s:Step){return s.swapping.includes(id)?'moving':s.comparing.includes(id)?'compare':s.active.includes(id)?'active':s.sorted.includes(id)?'settled':s.eliminated.includes(id)?'eliminated':'';}
export const AnimatedArray=memo(function AnimatedArray({step:s,bars=false,compact=false,reduced=false}:{step:Step;bars?:boolean;compact?:boolean;reduced?:boolean}){
 const max=Math.max(1,...s.array.map(v=>Math.abs(v.value)));const gap=compact?9:12,cell=compact?44:48;const width=Math.max(1,s.array.length)*(cell+gap)-gap;const linked=s.comparing.filter(id=>s.array.some(v=>v.id===id));
 return <div className={'viz-array-scroll '+(compact?'compact':'')}><div className={'viz-array '+(bars?'bars':'cards')} style={{width:Math.max(width,120),height:bars?240:125}} role="img" aria-label={s.array.length?`Values: ${s.array.map(v=>v.hole?'open slot':v.value).join(', ')}. ${s.description}`:'Empty array'}>
 {linked.length===2&&<svg className="comparison-connector" width={Math.max(width,120)} height="20" aria-hidden="true"><motion.path d={`M ${s.array.findIndex(v=>v.id===linked[0])*(cell+gap)+cell/2} 14 V 5 H ${s.array.findIndex(v=>v.id===linked[1])*(cell+gap)+cell/2} V 14`} initial={false} animate={{pathLength:1}}/></svg>}
 <AnimatePresence initial={false}>{s.array.map((v,i)=><motion.div key={v.id} className={`viz-value ${stateName(v.id,s)} ${v.hole?'hole':''}`} style={{width:cell}} initial={reduced?false:{opacity:0,y:-35}} animate={{x:i*(cell+gap),y:s.comparing.includes(v.id)?-10:0,opacity:s.eliminated.includes(v.id)?.28:1,scale:s.eliminated.includes(v.id)?.88:1}} exit={reduced?{opacity:0}:{opacity:0,y:-40}} transition={reduced?{duration:0}:{type:'spring',stiffness:220,damping:28}}>
 <motion.div className="value-shape" animate={{height:bars?(v.hole?36:45+(v.value-Math.min(0,...s.array.map(x=>x.value)))/Math.max(1,max-Math.min(0,...s.array.map(x=>x.value)))*115):52}} transition={{duration:reduced?0:.3}}><strong>{v.hole?'':v.value}</strong>{s.sorted.includes(v.id)&&<small aria-label="Fixed position">✓</small>}</motion.div><span className="value-index">{i}</span>
 {Object.entries(s.pointers).filter(([,n])=>n===i).map(([name])=><motion.span layoutId={`pointer-${name}`} key={name} className="viz-pointer" transition={{duration:reduced?0:.3}}>↑ {name}</motion.span>)}
 </motion.div>)}</AnimatePresence>
 {s.held&&<motion.div className="held-key" layoutId="held-key" initial={false} animate={{opacity:1}}><span>key</span><strong>{s.held.value}</strong></motion.div>}
 {!s.array.length&&<span className="viz-empty">Empty. Ready for a first value.</span>}
 </div></div>;
});
export const AnimatedNodes=memo(function AnimatedNodes({step:s,reduced=false}:{step:Step;reduced?:boolean}){const marker=useId().replace(/:/g,'');const height=Math.max(320,...s.nodes.map(n=>n.y+55));return <div className="viz-node-scroll"><svg className="viz-node-canvas" viewBox={`0 0 720 ${height}`} style={{minHeight:Math.min(height,420)}} role="img" aria-label={`${s.nodes.map(n=>n.label).join(', ')}. ${s.description}`}>
 <defs><marker id={marker} markerWidth="7" markerHeight="7" refX="5" refY="3.5" orient="auto"><path d="M0 0 L7 3.5 L0 7" fill="currentColor"/></marker></defs>
 <AnimatePresence initial={false}>{s.edges.map(e=>{const from=s.nodes.find(n=>n.id===e.from),to=s.nodes.find(n=>n.id===e.to);if(!from||!to)return null;const dx=to.x-from.x,dy=to.y-from.y,len=Math.max(1,Math.hypot(dx,dy)),x1=from.x+dx/len*23,y1=from.y+dy/len*23,x2=to.x-dx/len*28,y2=to.y-dy/len*28;const loop=e.from===e.to,paired=s.edges.some(other=>other.from===e.to&&other.to===e.from),bend=paired?36:0,mx=(x1+x2)/2-dy/len*bend,my=(y1+y2)/2+dx/len*bend;const hot=s.edgePath?s.edgePath.some((id,i)=>id===e.from&&s.edgePath![i+1]===e.to):s.active.includes(e.from)&&s.active.includes(e.to)||s.comparing.includes(e.from)&&s.comparing.includes(e.to);return <motion.g key={`${e.from}-${e.to}`} initial={false} animate={{opacity:1}} exit={{opacity:0}}><motion.path className={hot?'edge active':'edge'} initial={{pathLength:reduced?1:0}} animate={{d:loop?`M${from.x-16},${from.y-16} C${from.x-60},${from.y-80} ${from.x+60},${from.y-80} ${from.x+18},${from.y-20}`:paired?`M${x1},${y1} Q${mx},${my} ${x2},${y2}`:`M${x1},${y1} L${x2},${y2}`,pathLength:1}} transition={{duration:reduced?0:.45}} markerEnd={`url(#${marker})`}/>{e.weight!==undefined&&<g transform={`translate(${loop?from.x:((x1+x2)/2+mx)/2},${loop?from.y-54:((y1+y2)/2+my)/2})`}><rect x="-12" y="-11" width="24" height="20" rx="7" className="edge-weight-bg"/><text textAnchor="middle" y="4" className="edge-weight">{e.weight}</text></g>}</motion.g>})}</AnimatePresence>
 <AnimatePresence initial={false}>{s.nodes.map(n=><motion.g key={n.id} initial={reduced?false:{opacity:0,scale:.7}} animate={{x:n.x,y:n.y,opacity:1,scale:s.active.includes(n.id)?1.06:1}} exit={{opacity:0,scale:reduced?1:.8}} transition={reduced?{duration:0}:{type:'spring',stiffness:200,damping:26}} className={`viz-node ${stateName(n.id,s)}`}><circle r="23"/><text textAnchor="middle" dominantBaseline="central">{n.label}</text>{s.sorted.includes(n.id)&&<text className="node-check" x="20" y="-20">✓</text>}</motion.g>)}</AnimatePresence>
 {!s.nodes.length&&<text x="360" y="150" textAnchor="middle" className="empty-node-label">Empty structure</text>}
 </svg></div>});
function StackQueue({step:s,stack,reduced}:{step:Step;stack:boolean;reduced:boolean}){return <div className={stack?'viz-stack':'viz-queue'} role="img" aria-label={`${stack?'Stack, bottom to top':'Queue, front to rear'}: ${s.array.map(v=>v.value).join(', ')||'empty'}`}><span className="structure-rule">{stack?'LIFO · last in, first out':'FIFO · first in, first out'}</span><div className="structure-values"><AnimatePresence initial={false}>{s.array.map((v,i)=><motion.div layout key={v.id} className={`structure-value ${stateName(v.id,s)}`} initial={reduced?false:stack?{opacity:0,y:-50}:{opacity:0,x:50}} animate={{opacity:1,x:0,y:0}} exit={reduced?{opacity:0}:stack?{opacity:0,y:-50}:{opacity:0,x:-50}} transition={{duration:reduced?0:.35}}><strong>{v.value}</strong>{(stack?i===s.array.length-1:i===0)&&<span>{stack?'← top':'front'}</span>}{!stack&&i===s.array.length-1&&<span>rear</span>}</motion.div>)}</AnimatePresence>{!s.array.length&&<p className="viz-empty">Empty</p>}</div></div>}
const flowNodes=[{id:'entry',label:'Enter',x:110,y:60},{id:'condition',label:'Check',x:310,y:60},{id:'body',label:'Body',x:310,y:200},{id:'repeat',label:'Next',x:110,y:200},{id:'exit',label:'Exit',x:570,y:60},{id:'skip',label:'Skip',x:570,y:200}];
function LoopVisualizer({step:s,reduced,id}:{step:Step;reduced:boolean;id:string}){return <><div className="loop-caption">{id==='if-else'?'The condition chooses the If or Else branch; both paths return.':'Check → body → next → check. Break / return leave; continue skips the body.'}</div><AnimatedNodes reduced={reduced} step={{...s,nodes:id==='if-else'?flowNodes.filter(n=>n.id!=='repeat').map(n=>({...n,label:n.id==='body'?'If':n.id==='skip'?'Else':n.label})):flowNodes,edges:id==='if-else'?[{from:'entry',to:'condition'},{from:'condition',to:'body'},{from:'condition',to:'skip'},{from:'body',to:'exit'},{from:'skip',to:'exit'}]:[{from:'entry',to:'condition'},{from:'condition',to:'body'},{from:'body',to:'repeat'},{from:'repeat',to:'condition'},{from:'condition',to:'exit'},{from:'condition',to:'skip'},{from:'skip',to:'repeat'}],active:[s.phase==='alternate'?'skip':s.phase||'entry'],sorted:[],comparing:[]}}/>{s.array.length>0&&<AnimatedArray step={s} compact reduced={reduced}/>}</>}
export function VisualizationCanvas({algorithm,step,reduced=false,compact=false}:{algorithm:Algorithm;step:Step;reduced?:boolean;compact?:boolean}){
 return <div className={`visualization-canvas view-${algorithm.view} ${compact?'is-mini':''}`}>
 {algorithm.view==='flow'?<LoopVisualizer id={algorithm.id} step={step} reduced={reduced}/>:algorithm.view==='stack'||algorithm.view==='queue'?<StackQueue step={step} stack={algorithm.view==='stack'} reduced={reduced}/>:algorithm.view==='recursion'?<div className="recursion-stage"><span className="structure-rule">Call stack · waiting calls stay below</span><div className="call-tower"><AnimatePresence initial={false}>{step.frames.map((frame,i)=><motion.div layout key={`${i}-${frame}`} initial={reduced?false:{opacity:0,y:-20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:reduced?0:-20}} className={i===step.frames.length-1?'current-frame':''}><small>{i+1}</small>{frame}{i===step.frames.length-1&&<span>← active</span>}</motion.div>)}</AnimatePresence>{!step.frames.length&&<div className="return-value">{step.output.join(', ')||'Ready'}</div>}</div></div>:algorithm.view==='hash'?<div className="hash-stage"><div className="hash-formula">{step.variables.hash||'key % 7 → bucket'}</div>{step.groups.map((g,i)=><motion.div layout className={`hash-bucket ${step.pointers.bucket===i?'active':''}`} key={g.label}><span>{g.label}</span><i>→</i><div>{g.values.map(v=><motion.strong layout key={v} initial={{opacity:0}} animate={{opacity:1}}>{v}</motion.strong>)}{!g.values.length&&<small>empty</small>}</div></motion.div>)}</div>:<>{(algorithm.view==='nodes'||step.nodes.length>0)&&<AnimatedNodes step={step} reduced={reduced}/>} {(algorithm.view==='array'||algorithm.view==='bars')&&<AnimatedArray step={step} bars={algorithm.view==='bars'} compact={compact} reduced={reduced}/>}</>}
 {step.groups.length>0&&algorithm.view!=='hash'&&<div className="merge-groups" aria-label="Partition and merge hierarchy">{step.groups.map((g,i)=><motion.div layout key={`${g.label}-${i}`} style={{marginLeft:g.depth*12}} initial={{opacity:0}} animate={{opacity:1}} transition={{duration:reduced?0:.25}}><small>{g.label}</small><span>{g.values.map((v,j)=><motion.b layout key={j}>{v}</motion.b>)}</span></motion.div>)}</div>}
 {step.frontier.length>0&&<div className="frontier"><span>{algorithm.id==='dfs'||step.phase==='dfs'?'Stack · top at right':algorithm.id==='dijkstra'||step.phase==='dijkstra'?'Unsettled':'Queue · front at left'}</span><div>{step.frontier.map((v,i)=><motion.b layout key={`${v}-${i}`}>{v}</motion.b>)}</div></div>}
 {step.frames.length>0&&algorithm.view!=='recursion'&&<div className="frame-strip"><span>Calls</span>{step.frames.map((v,i)=><span key={`${v}-${i}`}>{v}</span>)}</div>}
 </div>;
}
