import {useEffect,useMemo,useRef,useState} from 'react';
import {motion,useReducedMotion} from 'motion/react';
import {Play,Pause,SkipBack,SkipForward,RotateCcw,ArrowLeft,Check,Lightbulb} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {VisualizationCanvas} from './Canvas';
import {usePlayback} from './usePlayback';
import {defaults,parseValues,validateInput,type Algorithm,type Input,type Step,type LearningRecord} from './engine';
import {graphCode,graphAlgorithms} from './graphs';
export function initialInput(a:Algorithm):Input{return{...defaults,values:a.defaultValues??defaults.values,operation:a.operations?.[0]??'',index:a.category==='Control flow'?(a.id==='nested-loops'?3:6):1,target:a.id==='nested-loops'?3:a.id==='continue'?2:5};}
function CodePanel({code,line}:{code:string;line:number}){const panel=useRef<HTMLDivElement>(null);useEffect(()=>{const active=panel.current?.querySelector('[aria-current="step"]') as HTMLElement|undefined;if(active&&panel.current){const p=panel.current;if(active.offsetTop<p.scrollTop||active.offsetTop+active.offsetHeight>p.scrollTop+p.clientHeight)p.scrollTop=Math.max(0,active.offsetTop-p.clientHeight*.4)}},[line]);return <section className="viz-code-panel"><div className="viz-panel-heading"><h2>Python, one operation at a time.</h2><span>Code</span></div><div className="viz-code-scroll" ref={panel}><pre aria-label="Python implementation">{code.split('\n').map((text,i)=><div key={i} aria-current={line===i+1?'step':undefined} className={line===i+1?'executing':''}><span aria-hidden="true">{i+1}</span><code>{text||' '}</code>{line===i+1&&<span className="sr-only">Current operation</span>}</div>)}</pre></div></section>}
export function VisualizationControls({playback,total}:{playback:ReturnType<typeof usePlayback>;total:number}){return <div className="visualization-controls"><div className="transport"><Button variant="ghost" size="icon" aria-label="Previous step" disabled={playback.index===0} onClick={()=>playback.seek(playback.index-1)}><SkipBack/></Button><Button onClick={playback.toggle} disabled={total<2} aria-label={playback.playing?'Pause playback':'Play playback'}>{playback.playing?<Pause/>:<Play/>}{playback.playing?'Pause':'Play'}</Button><Button variant="ghost" size="icon" aria-label="Next step" disabled={playback.index===total-1} onClick={()=>playback.seek(playback.index+1)}><SkipForward/></Button><Button variant="ghost" size="icon" aria-label="Reset playback" onClick={()=>playback.seek(0)}><RotateCcw/></Button></div><label className="viz-speed">Speed<select aria-label="Playback speed" value={playback.speed} onChange={e=>playback.setSpeed(Number(e.target.value))}>{[.25,.5,1,2].map(n=><option key={n} value={n}>{n}×</option>)}</select></label><div className="viz-timeline"><input type="range" aria-label="Algorithm timeline" min="0" max={total-1} value={playback.index} onChange={e=>playback.seek(Number(e.target.value))}/><span>Step {playback.index+1} / {total}</span></div></div>}
function predictionOptions(steps:Step[],index:number){const next=steps[index+1];if(!next)return [];const others=[...new Set(steps.map(s=>s.description).filter(s=>s!==next.description&&s!==steps[index].description))];const wrong=others.filter((_,i)=>i%Math.max(1,Math.floor(others.length/3))===0).slice(0,2);const options=[...wrong,next.description];const rotate=(index+1)%options.length;return [...options.slice(rotate),...options.slice(0,rotate)];}
export function Player({algorithm:a,onBack,onProgress,motionPaused,history}:{algorithm:Algorithm;onBack:()=>void;onProgress:(patch:Partial<LearningRecord>)=>void;motionPaused:boolean;history?:LearningRecord}){
 const [input,setInput]=useState(()=>initialInput(a)),[text,setText]=useState(()=>initialInput(a).values.join(', ')),[error,setError]=useState(''),[run,setRun]=useState(()=>({input:initialInput(a),serial:0}));
 const effective=useMemo(()=>a.id==='graph'?{...a,...(run.input.operation==='DFS'?{code:graphCode('DFS'),complexityNote:graphAlgorithms[1].complexityNote,space:graphAlgorithms[1].space}:run.input.operation==='Shortest path'?{code:graphCode('Shortest path'),best:graphAlgorithms[2].best,average:graphAlgorithms[2].average,worst:graphAlgorithms[2].worst,space:graphAlgorithms[2].space,complexityNote:graphAlgorithms[2].complexityNote}:{code:graphCode('BFS')})}:a,[a,run.input.operation]);
 const steps=useMemo(()=>a.generate(run.input),[a,run]);const playback=usePlayback(steps);const step=steps[playback.index];const systemReduced=useReducedMotion(),reduced=!!systemReduced||motionPaused;
 const [predicting,setPredicting]=useState(false),[answer,setAnswer]=useState<string|null>(null),[predictionCount,setPredictionCount]=useState(history?.predictions??0),[correctCount,setCorrectCount]=useState(history?.correct??0);
 const recorded=useRef(false),stage=useRef<HTMLDivElement>(null);const graph=a.id==='graph'||a.category==='Graph algorithms',scalar=['basic-recursion','factorial','fibonacci','if-else'].includes(a.id),control=a.category==='Control flow';
 useEffect(()=>{stage.current?.focus({preventScroll:true})},[]);
 useEffect(()=>{if(step.done&&!recorded.current){recorded.current=true;onProgress({completed:true})}},[step,onProgress]);
 useEffect(()=>{setPredicting(false);setAnswer(null)},[playback.index,run]);
 const apply=(operation?:string)=>{try{let values=parseValues(text,a.limit??12);if(operation&&a.type==='Structure'&&!graph){if(!step.done)throw Error('Finish this operation before applying another.');values=step.array.map(v=>v.value);}const next={...input,values,operation:operation??input.operation};validateInput(next,a);if(operation&&['Push','Enqueue','Insert','Add'].includes(operation)&&values.length>=(a.limit??12))throw Error(`Use at most ${a.limit??12} values. Start again with fewer values.`);a.generate(next);setRun({input:next,serial:run.serial+1});setError('');setPredicting(false);setAnswer(null);recorded.current=false;if(operation)setText(values.join(', '));}catch(e){setError((e as Error).message)}};
 useEffect(()=>{const key=(event:KeyboardEvent)=>{const target=event.target as HTMLElement;if(target.closest('input,textarea,select,button,a,[role="dialog"],[contenteditable=true]')||document.querySelector('[role="dialog"]'))return;if(event.key===' '){event.preventDefault();playback.toggle()}else if(event.key==='ArrowRight'){event.preventDefault();playback.seek(playback.index+1)}else if(event.key==='ArrowLeft'){event.preventDefault();playback.seek(playback.index-1)}else if(event.key.toLowerCase()==='r'){event.preventDefault();playback.seek(0)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[playback]);
 const options=useMemo(()=>predictionOptions(steps,playback.index),[steps,playback.index]);
 return <div className="viz-player" ref={stage} tabIndex={-1}><button className="text-link" onClick={onBack}><ArrowLeft size={17}/> All visualisations</button><header className="viz-player-intro"><div><span className="viz-category">{a.category}</span><h1>{a.name}</h1><p>{a.summary}</p></div><span className="viz-difficulty">{a.level}</span></header>
 <details className="viz-inputs"><summary>Make it yours <span>{graph?'Edit edges and start node':scalar?'Change n or value':control?'Change loop inputs':'Enter your own numbers'}</span></summary><form onSubmit={e=>{e.preventDefault();apply()}}>
 {!graph&&!scalar&&!control&&<label className="numbers-input">Numbers<input value={text} onChange={e=>setText(e.target.value)} placeholder="7, 2, 9, 1, 5, 3"/><small>Up to {a.limit??12} integers · −99 to 99 · empty is allowed</small></label>}
 {a.id==='return'&&<label>Numbers<input value={text} onChange={e=>setText(e.target.value)}/></label>}
 {graph?<><label className="edges-input">Directed edges: from, to, weight<textarea value={input.edges} onChange={e=>setInput({...input,edges:e.target.value})} rows={5}/><small>Example: A B 4 · at most 8 nodes / 16 edges · weights 0–99</small></label><label>Start<input maxLength={1} value={input.start} onChange={e=>setInput({...input,start:e.target.value.toUpperCase()})}/></label><label>Destination<input maxLength={1} value={input.end} onChange={e=>setInput({...input,end:e.target.value.toUpperCase()})}/></label></>:<>{(a.category==='Searching'||a.category==='Recursion'||a.type==='Structure'||['if-else','break','continue','nested-loops'].includes(a.id))&&a.id!=='tree-traversal'&&<label>{scalar&&a.id!=='if-else'?'n':a.id==='nested-loops'?'Columns (0–4)':a.type==='Structure'?'Value':'Target / value'}<input type="number" value={input.target} min={scalar&&a.id!=='if-else'?0:-99} max={a.id==='nested-loops'?4:a.id==='fibonacci'?6:scalar&&a.id!=='if-else'?8:99} onChange={e=>setInput({...input,target:Number(e.target.value)})}/></label>}{(control&&a.id!=='if-else'&&a.id!=='return'||['array','linked-list'].includes(a.id))&&<label>{control?a.id==='nested-loops'?'Rows (0–4)':'Loop count (0–12)':'Index (zero-based)'}<input type="number" min="0" max={a.id==='nested-loops'?4:12} value={input.index} onChange={e=>setInput({...input,index:Number(e.target.value)})}/></label>}</>}
 {a.operations&&<label>Operation<select value={input.operation} onChange={e=>setInput({...input,operation:e.target.value})}>{a.operations.map(op=><option key={op}>{op}</option>)}</select></label>}
 <Button type="submit">Visualise</Button></form></details>{error&&<p className="viz-error" role="alert">{error}</p>}
 <div className="viz-immersive"><div className="viz-teaching"><section className="viz-stage" aria-label={`${a.name} visualisation`}><div className="viz-stage-heading"><span>{step.done?'Complete':step.variables.pass?`Pass ${step.variables.pass}`:'Follow the movement'}</span><span className="viz-state-legend"><i/> active <b>✓</b> fixed / visited</span></div><VisualizationCanvas algorithm={effective} step={step} reduced={reduced}/>{Object.keys(step.variables).length>0&&<dl className="viz-variables">{Object.entries(step.variables).map(([name,value])=><div key={name}><dt>{name}</dt><dd>{String(value)}</dd></div>)}</dl>}</section>
 <VisualizationControls playback={playback} total={steps.length}/><section className="viz-explanation" aria-live={playback.playing?'off':'polite'}><h2>What’s happening?</h2><p>{step.description}</p>{step.output.length>0&&<div className="viz-output"><span>Output</span><samp>{step.output.join(' → ')}</samp></div>}</section>
 {a.type==='Structure'&&a.id!=='graph'&&<section className="viz-operations"><h2>Try an operation.</h2><p>Value: {input.target}{['array','linked-list'].includes(a.id)?` · index: ${input.index}`:''}. Change these under “Make it yours”. Finish playback before the next operation.</p><div>{a.operations?.map(op=><Button variant="outline" key={op} disabled={!step.done} onClick={()=>apply(op)}>{op}</Button>)}</div>{!step.done&&<button className="text-link" onClick={()=>playback.seek(steps.length-1)}>Finish this operation</button>}</section>}
 <section className="prediction-panel"><div><Lightbulb size={19}/><h2>Your turn.</h2></div>{playback.index<steps.length-1?<>{!predicting?<><p>Can you predict the next operation?</p><Button variant="outline" onClick={()=>{playback.pause();setPredicting(true)}}>Predict what happens next</Button></>:<><p>What happens immediately after this step?</p><div className="prediction-options">{options.map(option=><button disabled={answer!==null} key={option} onClick={()=>{setAnswer(option);const correct=option===steps[playback.index+1].description;setPredictionCount(predictionCount+1);setCorrectCount(correctCount+(correct?1:0));onProgress({predictions:predictionCount+1,correct:correctCount+(correct?1:0)})}}>{option}</button>)}</div>{answer&&<div role="status" className="prediction-feedback">{answer===steps[playback.index+1].description?'Exactly. ':`Next: ${steps[playback.index+1].description} `}<button className="text-link" onClick={()=>playback.seek(playback.index+1)}>Watch the next step →</button></div>}</>}</>:<><p><Check size={16}/> You reached the end. Rewind to test your prediction.</p><Button variant="outline" onClick={()=>playback.seek(Math.max(0,Math.floor(steps.length/3)))}>Try a prediction</Button></>}</section>
 </div><div className="viz-reference"><CodePanel code={effective.code} line={step.codeLine}/><section className="complexity-panel"><h2>How the work grows.</h2><dl>{[['Best',effective.best],['Average',effective.average],['Worst',effective.worst],['Space',effective.space]].map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}</dl><p>{effective.complexityNote}</p></section><p className="viz-shortcuts"><kbd>Space</kbd> play / pause · <kbd>←</kbd> <kbd>→</kbd> step · <kbd>R</kbd> reset<br/>Shortcuts work outside input fields and buttons.</p></div></div>
 </div>;
}
