import {useCallback,useEffect,useMemo,useState} from 'react';
import {AnimatePresence,LayoutGroup,motion,useReducedMotion} from 'motion/react';
import {ArrowRight,Search,Play,Pause,RotateCcw,Sparkles,Check} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {algorithms,categories} from './catalogue';
import {VisualizationCanvas} from './Canvas';
import {Player,initialInput} from './Player';
import {usePlayback} from './usePlayback';
import type {Algorithm,LearningProgress,LearningRecord} from './engine';
import './visualisations.css';
const featured=['binary-search','insertion-sort','stack'];
function Artwork({algorithm:a}:{algorithm:Algorithm}){const bars=a.category==='Sorting'||a.category==='Searching';return <div className={`algorithm-art ${bars?'art-bars':'art-path'}`} aria-hidden="true">{bars?[3,1,5,2,4].map((n,i)=><span style={{height:25+n*12}} key={i}/>):[0,1,2,3].map(i=><span key={i}>{a.category==='Recursion'?'ƒ':i+1}</span>)}</div>}
function AlgorithmCard({algorithm:a,onOpen,progress}:{algorithm:Algorithm;onOpen:(id:string)=>void;progress?:LearningRecord}){return <motion.button className="algorithm-card" onClick={()=>onOpen(a.id)} whileHover={{y:-4}} whileTap={{scale:.985}} transition={{duration:.2}}><span className="algorithm-card-meta">{a.category}<span>{progress?.completed?<><Check size={14}/> Explored</>:a.level}</span></span><h3>{a.name}</h3><p>{a.summary}</p><Artwork algorithm={a}/><span className="algorithm-card-link">Explore <ArrowRight size={18}/></span></motion.button>}
function HeroDemo({motionPaused,onBasics}:{motionPaused:boolean;onBasics:()=>void}){const a=algorithms.find(a=>a.id==='insertion-sort')!;const steps=useMemo(()=>a.generate({...initialInput(a),values:[7,2,9,1,5,3]}),[a]);const playback=usePlayback(steps),reduced=useReducedMotion();const [started,setStarted]=useState(false);useEffect(()=>{if(started||reduced||motionPaused)return;const timer=setTimeout(()=>{playback.toggle();setStarted(true)},1400);return()=>clearTimeout(timer)},[started,reduced,motionPaused,playback.toggle]);useEffect(()=>{if(reduced||motionPaused)playback.pause()},[reduced,motionPaused,playback.pause]);return <LayoutGroup id="mini-demo"><motion.div className="visualisation-hero-demo" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:.4,duration:.4}}><div className="demo-caption"><span>Insertion sort, in motion.</span><div><button aria-label={playback.playing?'Pause demo':'Play demo'} onClick={()=>{setStarted(true);playback.toggle()}}>{playback.playing?<Pause size={16}/>:<Play size={16}/>}</button><button aria-label="Reset demo" onClick={()=>{setStarted(true);playback.seek(0)}}><RotateCcw size={15}/></button></div></div><VisualizationCanvas algorithm={a} step={steps[playback.index]} reduced={!!reduced||motionPaused} compact/><button className="demo-explanation" onClick={onBasics}>{steps[playback.index].description}<ArrowRight size={16}/></button></motion.div></LayoutGroup>}
export default function VisualizationPage({learning,onLearning,motionPaused}:{learning:LearningProgress;onLearning:(next:LearningProgress)=>void;motionPaused:boolean}){
 const reduced=useReducedMotion();
 const [selected,setSelected]=useState<string|null>(null),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[level,setLevel]=useState('All levels'),[type,setType]=useState('All types');
 const open=useCallback((id:string)=>{setSelected(id);onLearning({...learning,[id]:{...learning[id],viewedAt:Date.now()}});window.scrollTo({top:0,behavior:'instant'})},[learning,onLearning]);
 const record=useCallback((patch:Partial<LearningRecord>)=>{if(selected)onLearning({...learning,[selected]:{...learning[selected],viewedAt:learning[selected]?.viewedAt??Date.now(),...patch}})},[learning,onLearning,selected]);
 const current=algorithms.find(a=>a.id===selected);const filtered=algorithms.filter(a=>(category==='All'||a.category===category)&&(level==='All levels'||a.level===level)&&(type==='All types'||a.type===type)&&`${a.name} ${a.summary} ${a.category}`.toLowerCase().includes(query.toLowerCase()));
 const recent=Object.entries(learning).sort((a,b)=>b[1].viewedAt-a[1].viewedAt).map(([id])=>algorithms.find(a=>a.id===id)).filter((a):a is Algorithm=>!!a).slice(0,4);
 const recommended=algorithms.filter(a=>featured.includes(a.id)&&!learning[a.id]?.completed);if(!recommended.length)recommended.push(...algorithms.filter(a=>!learning[a.id]?.completed).slice(0,3));
 return <div className="visualisations-page"><AnimatePresence mode="wait" initial={false}>{current?<motion.div key={current.id} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:.18}}><LayoutGroup id={current.id}><Player key={current.id} algorithm={current} motionPaused={motionPaused} onBack={()=>{setSelected(null);window.scrollTo({top:0,behavior:'instant'})}} onProgress={record} history={learning[current.id]}/></LayoutGroup></motion.div>:<motion.div key="visual-library" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><section className="visualisation-hero"><motion.div initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{duration:.5}}><span className="viz-category">Interactive visualisations</span><h1>See the algorithm.</h1><p>Don’t just learn how algorithms work.<br/>Watch them think.</p></motion.div><HeroDemo motionPaused={motionPaused} onBasics={()=>open('insertion-sort')}/><motion.div className="visualisation-hero-actions" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.6}}><Button size="lg" onClick={()=>document.getElementById('algorithm-library')?.scrollIntoView({behavior:motionPaused||reduced?'instant':'smooth'})}>Explore algorithms <ArrowRight/></Button><button className="text-link" onClick={()=>open('for-loop')}>Start with the basics <ArrowRight size={16}/></button></motion.div><p className="viz-library-count">{algorithms.length} visualisations · one operation at a time</p></section>
 {recent.length>0&&<section className="recent-visualisations"><h2>Pick up a thought.</h2><div>{recent.map(a=><button key={a.id} onClick={()=>open(a.id)}>{a.name}{learning[a.id]?.completed?<Check size={15}/>:<ArrowRight size={15}/>}</button>)}</div></section>}
 <section id="algorithm-library" className="algorithm-library"><div className="viz-library-heading"><div><h2>A clearer way to learn.</h2><p>Change the input. Follow a value. Predict the next move.</p></div><span>{Object.values(learning).filter(v=>v.completed).length} explored</span></div><div className="algorithm-filters"><label className="viz-search"><Search size={18}/><input type="search" aria-label="Search visualisations" placeholder="Find an algorithm or idea…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Visualisation difficulty" value={level} onChange={e=>setLevel(e.target.value)}>{['All levels','Foundation','Core','Stretch'].map(l=><option key={l}>{l}</option>)}</select><select aria-label="Visualisation type" value={type} onChange={e=>setType(e.target.value)}>{['All types','Algorithm','Structure','Control flow'].map(l=><option key={l}>{l}</option>)}</select></div><div className="algorithm-categories" aria-label="Visualisation categories">{['All',...categories].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div>
 {category==='All'&&!query&&level==='All levels'&&type==='All types'&&recommended.length>0&&<section className="recommended-algorithms"><h3><Sparkles size={17}/> A good place to go next.</h3><div className="algorithm-grid">{recommended.slice(0,3).map(a=><AlgorithmCard key={a.id} algorithm={a} onOpen={open} progress={learning[a.id]}/>)}</div></section>}
 <div className="viz-result-count">{filtered.length} visualisations</div><div className="algorithm-grid">{filtered.map(a=><AlgorithmCard key={a.id} algorithm={a} onOpen={open} progress={learning[a.id]}/>)}</div>{!filtered.length&&<div className="viz-no-results"><h3>No matches yet.</h3><p>Try a different topic or clear your filters.</p><Button variant="outline" onClick={()=>{setQuery('');setCategory('All');setLevel('All levels');setType('All types')}}>Clear filters</Button></div>}</section></motion.div>}</AnimatePresence></div>;
}
